export const AllLawAbbrs = [
  "ZustVO des Ministeriums f\u00fcr Verkehr NRW",
  "EStGemAntVO 2024  2025 und 2026 NRW",
  "Th\u00fcrAGPa\u00dfGPAuswGeIDKG TH",
  "S\u00e4chsAPO-Justiz-JVD 2014 SN",
  "JustG NRW\u00a7123Bef\u00dcV NRW",
  "S\u00e4chsSchiedsG\u00fctStG SN",
  "InstallateurHeizungsbauerMstrV",
  "S\u00e4chsStudPlVergabeVO SN",
  "BeamtdiszZustVO MKULNV NRW",
  "2. \u00c4ndStV StBVBek NRW",
  "BeamtDiszZustVO MFKJKS NRW",
  "BinSchUOuBinSchPatentVAbwV",
  "Th\u00fcrHhG 2016/2017 TH",
  "S\u00e4chsAGPassPAuswG SN",
  "Th\u00fcrHhG 2008/2009 TH",
  "BesVersAnpG 2009/2010 NRW",
  "Th\u00fcrAGSGB XII-DVO TH",
  "S\u00e4chsS\u00dcGArtG SN",
  "BesVersAnpG 2011/2012 NRW",
  "BesVersAnpG 2015/2016 NRW",
  "BesVersAnpG 2013/2014 NRW",
  "Th\u00fcrHhG 2018/2019 TH",
  "Th\u00fcrHhG 2013/2014 TH",
  "AG TierGesG TierNebG NRW",
  "S\u00e4chsLJagdG 1991 SN",
  "ZustVO SGB IX SchwbR NRW",
  "StudienplatzvergabeVO SL",
  "Th\u00fcrGleichG 1998 TH",
  "2. \u00c4ndStV StBV NRW",
  "S\u00e4chsFl\u00fcAG SN",
  "S\u00e4chsKrWBodSchG SN",
  "Fl\u00fcAG\u00c4ndG NRW",
  "S\u00e4chsArchG 2002 SN",
  "Th\u00fcrJKostG 2009 TH",
  "Th\u00fcrAllgVwKostO TH",
  "HolzEinschlBeschrV2021",
  "S\u00e4chsIngG 1993 SN",
  "S\u00e4chsUVPG 2007 SN",
  "GoldSilberschmiedMstrV",
  "6. SchulR\u00c4ndG NRW",
  "SGBXII\u00a728RSV09 HH",
  "Th\u00fcr\u00d6PNVG TH",
  "FrSaftErfrischGetrTeeV",
  "S\u00e4chsJAPO 2006 SN",
  "S\u00e4chsEJustizVO SN",
  "Th\u00fcrFl\u00fcAG TH",
  "S\u00e4chsLPlG 2010 SN",
  "GemHVO Doppik 2010 LSA",
  "S\u00e4chsHSFG 2013 SN",
  "9. SchulR\u00c4ndG NRW",
  "PflanzTechnAusbStEignV",
  "GO S\u00e4chsVerfGH SN",
  "OLGHE\u00dcbertrVO NRW",
  "HSP\u00f6V NRW-FbV NRW",
  "VAPh\u00f6hDL 1991 NRW",
  "S\u00e4chsS\u00dcG SN",
  "VergabeVO Stiftung BW",
  "Th\u00fcrLbVO 1995 TH",
  "LBS NordWest-StVG NRW",
  "B\u00fcrgEntschDV NRW",
  "BayVersR\u00fccklG BY",
  "Th\u00fcrNRSchutzG TH",
  "Th\u00fcrAGSGB XII TH",
  "Verk\u00fcndungsG LSA",
  "Pass-PAusw-eIDK-AG BW",
  "DeutschePostAGDiszAnO",
  "GepBetrWMAProBusManFV",
  "Nds. AG SGB IX/XII NI",
  "S\u00e4chsRiG 2004 SN",
  "VersWerk\u00c4ndG NRW",
  "Th\u00fcrLPlG 2007 TH",
  "PO-FeP-Hochschule NRW",
  "S\u00e4chsABG 1999 SN",
  "1. B\u00fcrokAbbG NRW",
  "InformationsTechMstrV",
  "S\u00e4chsPolOrgVO SN",
  "DialogMarkFachkBAusbV",
  "S\u00e4chsNRG 1997 SN",
  "S\u00e4chsBauPAVO SN",
  "ZZV WS 2021/2022 NRW",
  "S\u00e4chsAG G 10 SN",
  "ZZV WS 2014/2015 NRW",
  "ZZV WS 2017/2018 NRW",
  "TexModSchneiderAusbV",
  "ZZV WS 2022/2023 NRW",
  "ZZV WS 2015/2016 NRW",
  "Th\u00fcrHhG 2021 TH",
  "Th\u00fcrVerfSchG TH",
  "S\u00e4chsBG 2009 SN",
  "ZZV WS 2020/2021 NRW",
  "Th\u00fcrHhG 2024 TH",
  "ZZV WS 2024/2025 NRW",
  "S\u00e4chsArchivG SN",
  "BundStiftBaukultErrG",
  "RevierjagdMeisterPrV",
  "10. S\u00e4chsKVZ SN",
  "ZZV WS 2008/2009 NRW",
  "BesVersAnpG 2008 NRW",
  "Th\u00fcrMeldeG94 TH",
  "Schul\u00c4ndG03 NRW",
  "Th\u00fcrHhG 2022 TH",
  "BremSchulG\u00c4G HB",
  "Th\u00fcrKWO 1994 TH",
  "VersR\u00fcckArtG SN",
  "ZZV WS 2013/2014 NRW",
  "ZZV WS 2019/2020 NRW",
  "LV \u00a7 22 LRKG RP",
  "LBS NordWest-StV NRW",
  "Th\u00fcrRiG 1994 TH",
  "PflanzentechMeistPrV",
  "Th\u00fcrAGSGB II TH",
  "Th\u00fcrHhG 2020 TH",
  "S\u00e4chsNatSchG SN",
  "ZZV WS 2023/2024 NRW",
  "IndMstrKunstStFortbV",
  "LwErzgSchulproTeilnV",
  "ZZV WS 2011/2012 NRW",
  "ZZV WS 2010/2011 NRW",
  "S\u00e4chsVerfGHG SN",
  "ZZV WS 2016/2017 NRW",
  "Th\u00fcrHhG 2015 TH",
  "ZZV WS 2009/2010 NRW",
  "NatSchG LSA 2004 LSA",
  "Th\u00fcrS\u00dcG TH",
  "Preis\u00dcZustV NRW",
  "TextilgestalterMstrV",
  "S\u00e4chsPresseG SN",
  "Th\u00fcrHhG 2011 TH",
  "\u00c4ndStV StBV NRW",
  "Th\u00fcrHhG 2023 TH",
  "AG-SGBIIRV\u00c4G SH",
  "HNSPflichtVersBeschV",
  "ZZV WS 2018/2019 NRW",
  "Th\u00fcrHhG 2012 TH",
  "Vers\u00c4EinglG NRW",
  "S\u00e4chsAGVermG SN",
  "S\u00e4chsKomKBVO SN",
  "ZZV WS 2012/2013 NRW",
  "EuRAG\u00dcbertV NRW",
  "Th\u00fcrHhG 2010 TH",
  "Th\u00fcrHhG 2005 TH",
  "S\u00e4chsVwVfZG SN",
  "HessAbgG-Ent2017 HE",
  "HmbS\u00dcBestVO HH",
  "S\u00e4chsVwOrgG SN",
  "MetallbInstrmMAusbV",
  "HessAbgG-Ent2009 HE",
  "HessAbgG-Ent2019 HE",
  "NVersR\u00fccklG NI",
  "HessAbgG-Ent2022 HE",
  "Th\u00fcrBG 1999 TH",
  "S\u00e4chsFischG SN",
  "SchulG\u00a796V NRW",
  "HessAbgG-Ent2014 HE",
  "DialogMarkKfmBAusbV",
  "1. JAPO\u00c4ndV RP",
  "TelekomErnAnOErgAnO",
  "MilchTechnAusbEignV",
  "HessAbgG-Ent2015 HE",
  "Th\u00fcrVerfGHG TH",
  "ZZV hF WS 21/22 NRW",
  "AnerkSparkAusbAufhV",
  "S\u00e4chsSchulG SN",
  "HAG/SGB XII 2004 HE",
  "HessAbgG-Ent2013 HE",
  "ZZV hF WS 17/18 NRW",
  "ZustVO AG Straf NRW",
  "ZZV hF WS 10/11 NRW",
  "B\u00a722cGVGVO NRW",
  "Th\u00fcrBodSchG TH",
  "HessAbgG-Ent2010 HE",
  "HVersR\u00fccklG HE",
  "ZZV hF WS 18/19 NRW",
  "ElekMaschBBBiGAusbV",
  "ZZV hF WS 19/20 NRW",
  "ZZV hF WS 23/24 NRW",
  "GVEntschVO 1998 NRW",
  "HessAbgG-Ent2016 HE",
  "GBBerG\u00a76VO NRW",
  "HAGBNatSchG 2010 HE",
  "VersR\u00fccklG Bln",
  "Th\u00fcrBPBahnG TH",
  "ZZV hF WS 13/14 NRW",
  "ZZV hF WS 16/17 NRW",
  "BeamtZustVO LRH NRW",
  "ZZV hF WS 14/15 NRW",
  "S\u00e4chsEigBVO SN",
  "ZZV hF WS 22/23 NRW",
  "Th\u00fcrAGArbGG TH",
  "FA\u00c4ndG 2012 HE",
  "KfzMechaAusbErprobV",
  "9. S\u00e4chsKVZ SN",
  "S\u00e4chsPersVG SN",
  "HessAbgG-Ent2023 HE",
  "ZZV hF WS 09/10 NRW",
  "ZZV hF WS 15/16 NRW",
  "ZZV hF WS 11/12 NRW",
  "HessAbgG-Ent2012 HE",
  "Th\u00fcrBG 2009 TH",
  "ZZV hF WS 08/09 NRW",
  "HessAbgG-Ent2018 HE",
  "Th\u00fcrGerOrgG TH",
  "ZupfinstrumentAusbV",
  "ZZV hF WS 12/13 NRW",
  "HessAbgG-Ent2024 HE",
  "HessAbgG-Ent2011 HE",
  "BauKaG NRW 2003 NRW",
  "Th\u00fcrArchivG TH",
  "ZZV hF WS 20/21 NRW",
  "ElekMaschBHwOAusbV",
  "Th\u00fcrRiStAG TH",
  "Th\u00fcrBauGVO TH",
  "RDLG\u00dcbtrV Bln",
  "Th\u00fcrLaufbG TH",
  "Th\u00fcrStiftG TH",
  "S\u00e4chsKomWO SN",
  "BremAGKrW-/AbfG HB",
  "EichendorffPlakErl",
  "Th\u00fcrAGVwGO TH",
  "S\u00e4chsJagdG SN",
  "PflSchSaatgAnwendV",
  "HBadHolzhAnVfg NRW",
  "Th\u00fcrFischG TH",
  "Wahlpr\u00fcfG NRW",
  "S\u00e4chsGleiG SN",
  "HerrentunnelMautHV",
  "2. BStrStraffG NRW",
  "RDG-Aufg\u00dcV HB",
  "ErnuEntlBMJAno2008",
  "BbgG\u00fcteStG BB",
  "Th\u00fcrHeilBG TH",
  "BremKJFF\u00f6G HB",
  "FlugGerElektrAusbV",
  "BauPr\u00fcfVO NRW",
  "Th\u00fcrErmStA TH",
  "VersR\u00fccklG BW",
  "StromuEnergieStBek",
  "KapVO NRW 2017 NRW",
  "S\u00e4chsAGSGB SN",
  "Wp\u00dcGKonzV NRW",
  "S\u00e4chsWahlG SN",
  "MDRVerm\u00f6gG TH",
  "ServicefahrerAusbV",
  "UruguaySozSichAbkG",
  "S\u00e4chsBestG SN",
  "SchuhfIndMstFortbV",
  "S\u00e4chsKiStG SN",
  "Th\u00fcrSammlG TH",
  "S\u00e4chsWaldG SN",
  "MedienBTMstrFortbV",
  "S\u00e4chsStatG SN",
  "EinkFachwBAProPPrV",
  "DIBt-\u00dctVO NRW",
  "ZustVO HumanAM NRW",
  "RDGAufg\u00dcV LSA",
  "S\u00e4chsEntEG SN",
  "MechatronikerAusbV",
  "EntsorgFondsGZahlV",
  "InfoElekAusbErprbV",
  "MontanMitbestGErgG",
  "Th\u00fcrAGKrWG TH",
  "SubvMi\u00dfbrG SN",
  "KfzServMechErprobV",
  "S\u00e4chsDSchG SN",
  "S\u00e4chsAGBMG SN",
  "Th\u00fcrAGInsO TH",
  "VersImmoDarlSachkV",
  "Th\u00fcrPersVG TH",
  "NachbG Schl.-H. SH",
  "\u00dcberlassV NRW",
  "Th\u00fcrSchulG TH",
  "SaubFahrzeugBeschG",
  "AgrarservMeistPrV",
  "KfzHPflVersVAufhV",
  "BMJVBhWidVertrAnO",
  "ZustVO MWEIMH NRW",
  "ZustVO Schule NRW",
  "FeinwerkMechMstrV",
  "TechnProdDesAusbV",
  "ZelterPlaketteErl",
  "Hess. FFG 1954 HE",
  "Brem\u00d6PNVG HB",
  "S\u00e4chsRAVG SN",
  "BeschaffRlTMIK TH",
  "ProdMechTextAusbV",
  "2.Rdf\u00c4ndG MV",
  "Fehl\u00c4ndG NRW",
  "HwFwBAProKaufmMFV",
  "S\u00e4chsAZVO SN",
  "ErsatzbaustoffVEV",
  "BMVgWidKlaZustAnO",
  "WaStrGGemGebrErmV",
  "BauO NRW 2018 NRW",
  "BMVgBeamtVZustAnO",
  "MaurerBetonbMstrV",
  "SchLichtReklAusbV",
  "S\u00e4chsVwVG SN",
  "Wahlpr\u00fcfG HH",
  "AG BAf\u00f6G NRW",
  "PfleBeteiligungsV",
  "HolzbInstrmMAusbV",
  "S\u00e4chsOWiG SN",
  "S\u00e4chsBhVO SN",
  "DirektZahlDurchfV",
  "RechPr\u00fcfG HB",
  "Th\u00fcrKiStG TH",
  "Th\u00fcrAGBGB TH",
  "OrthopschuhmAusbV",
  "IMPMedBAProPrFPrV",
  "S\u00e4chsBRKG SN",
  "StudVVO-Stift Bln",
  "VSt\u00e4ttVO NRW",
  "Th\u00fcrAGBMG TH",
  "BauPr\u00fcfVO MV",
  "S\u00e4chsMinG SN",
  "VulkReifMechMstrV",
  "BauVorlVO 2009 SH",
  "KampfmittelVO NRW",
  "Th\u00fcrStatG TH",
  "Th\u00fcrAGFGO TH",
  "Th\u00fcrGemHV TH",
  "DirektZahlDurchfG",
  "FischwAusbStEignV",
  "S\u00e4chsLKrO SN",
  "AGBGB Schl.-H. SH",
  "BMinBFBeihZustAnO",
  "BMASGBWidVertrAnO",
  "BwEhrZErlNeufErlG",
  "Th\u00fcrRettG TH",
  "LWKGFBezBestV NRW",
  "ZustVO TierAM NRW",
  "Th\u00fcrBestG TH",
  "Th\u00fcrVwVfG TH",
  "S\u00e4chsStrG SN",
  "S\u00e4chsGemO SN",
  "Th\u00fcrDSchG TH",
  "25. LB\u00c4G Bln",
  "Th\u00fcrSubvG TH",
  "AusbDienstLArbbV5",
  "TechnModellbAusbV",
  "Th\u00fcrVwZVG TH",
  "S\u00e4chsBesG SN",
  "BergbauTechnAusbV",
  "ChemikAusbErprobV",
  "TextilIndMeistPrV",
  "BMWiBhWidVertrAnO",
  "ArbPlSchGAbschn3V",
  "KautVerfMechAusbV",
  "FertigPlTischlPrV",
  "AG-SGB II/BKGG SH",
  "FAMG 2023/2024 SN",
  "Th\u00fcrKapVO TH",
  "Th\u00fcrAGSGG TH",
  "RDGAufg\u00dcV SL",
  "KorruptionsbG NRW",
  "ElektroGBattGGebV",
  "BeamtZustV FM NRW",
  "Th\u00fcrWaldG TH",
  "LogistikKfmFortbV",
  "Th\u00fcrAGGVG TH",
  "S\u00e4chsPVDG SN",
  "HmbPersVG 1979 HH",
  "LandBauTMechAusbV",
  "S\u00e4chsAbgG SN",
  "S\u00e4chsWprG SN",
  "MilchLAusbStEignV",
  "S\u00e4chsDSUG SN",
  "FluthilfeOrdenErl",
  "VersFondsG S-H SH",
  "\u00d6ffOrdnOG HB",
  "ServKflLuftvAusbV",
  "S\u00e4chsPRG SN",
  "HBG 2011/2012 SN",
  "BVerfGE20100707b",
  "Gr/AufwE 2013 TH",
  "BauGebVO 2009 SH",
  "PharmAusbErprobV",
  "ZustVOSchAuf NRW",
  "DSG LSA 2016 LSA",
  "PapierTechnAusbV",
  "Gr/AufwE 2020 TH",
  "S\u00e4chsPBG SN",
  "PrfgZFrankrGlStV",
  "KitaF\u00f6G Bln",
  "StVUnfStatG1990V",
  "FotoMedienFAusbV",
  "AutomAusbErprobV",
  "SpielzHerstAusbV",
  "AGSGB II/BKGG SL",
  "DBSchichtZulErhV",
  "TelekomBeihAZAnO",
  "S\u00e4chsTGV SN",
  "FlugGerMechAusbV",
  "AnalgetikaWarnHV",
  "Th\u00fcrBVVG TH",
  "ElektroTechMstrV",
  "BremGebBeitrG HB",
  "KundenbTischlPrV",
  "Gr/AufwE 2012 TH",
  "LHG 2017/2018 RP",
  "AgrarZahlVerpflG",
  "Gr/AufwE 2018 TH",
  "VSt\u00e4ttVO SL",
  "Th\u00fcrJAPO TH",
  "Gr/AufwE 2017 TH",
  "ChemOzonSchichtV",
  "LHG 2012/2013 RP",
  "TierSeuchErEinfV",
  "SegelmacherAusbV",
  "RLZelterPlakette",
  "LHG 2023/2024 RP",
  "AbwEmissionV NRW",
  "Th\u00fcrAIKG TH",
  "VerwGebO IFG NRW",
  "Th\u00fcrMinG TH",
  "S\u00e4chsRKG SN",
  "StrEKrRZustV NRW",
  "Th\u00fcrSpkG TH",
  "ZustVO ArbtG NRW",
  "HWKraftStAbV2021",
  "HBG 2019/2020 SN",
  "S\u00e4chsFFG SN",
  "RettAPO 2012 NRW",
  "HZG NRW 1993 NRW",
  "LBG NRW 1981 NRW",
  "Gr/AufwE 2021 TH",
  "SHStatG1985AussV",
  "Gr/AufwE 2022 TH",
  "AgrarZahlVerpflV",
  "HBG 2023/2024 SN",
  "PferdeWAusbEignV",
  "PO-Externe-A NRW",
  "HBG 2021/2022 SN",
  "MtDFmEloAufklVDV",
  "SKPersStruktAnpG",
  "HBG 2017/2018 SN",
  "HG 2012/2013 LSA",
  "S\u00e4chsLVO SN",
  "HBG 2015/2016 SN",
  "Bay\u00d6PNVG BY",
  "AgrarAusbStEignV",
  "HolzSpielzMAusbV",
  "DruckverarbAusbV",
  "HG 2015/2016 LSA",
  "VertrBMinFSFJAnO",
  "BremBesG 1999 HB",
  "Th\u00fcrUVPG TH",
  "S\u00e4chsJAG SN",
  "AufbewJustVO NRW",
  "RestMAProRestPrV",
  "MedInfoFAngAusbV",
  "S\u00e4chsHZG SN",
  "Gr/AufwE 2015 TH",
  "UStAufteilVO NRW",
  "BfArMWidVertrAnO",
  "HBG 2013/2014 SN",
  "HolzBautSchAusbV",
  "BMFSFJWidZustAnO",
  "HG 2010/2011 LSA",
  "S\u00e4chsKHG SN",
  "ChemBiozidMeldeV",
  "TWirtAusbStEignV",
  "KredInstNdlAufhG",
  "MFBAProMediaFPrV",
  "BVerfGE20100707c",
  "MarineFlaggenAnO",
  "Th\u00fcrAzVO TH",
  "HG2005/2006G LSA",
  "Gr/AufwE 2023 TH",
  "HartwSaatgAnerkV",
  "PflanzTechnAusbV",
  "IndMstrPapierPrV",
  "OberflbeschAusbV",
  "SportFachwFortbV",
  "S\u00e4chsSFG SN",
  "S\u00e4chsGDG SN",
  "RohrLeitErrG NRW",
  "RotklSaatgAnerkV",
  "BestattG 1988 HH",
  "ChemKlimaschutzV",
  "Th\u00fcrAbgG TH",
  "Gr/AufwE 2019 TH",
  "BauPGHeizkesselV",
  "S\u00e4chsUKG SN",
  "HG 2008/2009 LSA",
  "S\u00e4chsVSG SN",
  "FachbauTischlPrV",
  "PersVerkFwFortbV",
  "AusglAbgSGBIXBek",
  "MeldD\u00dcV NRW",
  "Th\u00fcrStrG TH",
  "KryptoWTransferV",
  "HBG 2009/2010 SN",
  "POSTDIENSTErnAnO",
  "S\u00e4chsKAG SN",
  "HG 2017/2018 LSA",
  "LoBUntLBEinG NRW",
  "GtDFmEloAufklVDV",
  "NOKTierSeuchSchV",
  "VermGebV 2014 RP",
  "S\u00e4chsNSG SN",
  "BauMaschMeistPrV",
  "RVWZPauschBeitrV",
  "VAPbD LG 2.2 NRW",
  "BDGBIBBBMinBFAnO",
  "NotRettLfzZV NRW",
  "IndMstElektroPrV",
  "S\u00e4chsFAG SN",
  "Th\u00fcrRAVG TH",
  "NichtRSchutzG MV",
  "AGPassGPAuswG RP",
  "RDG/GwG-ZustV BB",
  "WaffGBundFreistV",
  "HG 2020/2021 LSA",
  "LHG 2009/2010 RP",
  "Gr/AufwE 2014 TH",
  "FideiKAuflRAufhG",
  "PatBeteiligungsV",
  "Gr/AufwE 2011 TH",
  "AbwasserMeistPrV",
  "VerfSchG-LSA LSA",
  "Nds. S\u00dcG NI",
  "Bbg AG-SGB II BB",
  "KunstHG 1987 NRW",
  "S\u00e4chsHSG SN",
  "Th\u00fcrNatG TH",
  "AusbvermErstattV",
  "AltesLandPflSchV",
  "KrW-/AbfGBln Bln",
  "LHG 2019/2020 RP",
  "Gr/AufwE 2016 TH",
  "LHG 2014/2015 RP",
  "BVerfGE200920512",
  "Gr/AufwE 2024 TH",
  "FStrPrivFinBestV",
  "Th\u00fcrFGtG TH",
  "LandBauMechMstrV",
  "AgrarErzAnpBeihV",
  "BVerfGE20100706b",
  "EinwirkungsBergV",
  "APO VwB 2009 NRW",
  "Th\u00fcrRKGV TH",
  "StudPlVergVO LSA",
  "OfenLufthBAusbV",
  "EinsatzMedBWErl",
  "BVerfGE20220407",
  "BVerfGE20120718",
  "PostbankZustAnO",
  "BVerfGE20180919",
  "DVO VIVBVEG NRW",
  "BVerfGE20091117",
  "BVerfGE20180523",
  "POSTDIENSTBRAnO",
  "HG 2023/2024 HE",
  "BVerfGE20100504",
  "BVerfGE20110111",
  "BVerfGE20160921",
  "SattlFeintMstrV",
  "BVerfGE20080312",
  "BVerfGE20111109",
  "BVerfGE20190129",
  "RVBeitrSBek2022",
  "FlGlasTechAusbV",
  "BVerfGE20100302",
  "TextilGestAusbV",
  "NatSchG 2005 BW",
  "BVerfGE20181016",
  "BVerfGE20070228",
  "BVerfGE20180606",
  "BVerfGE20181128",
  "Th\u00fcrBKG TH",
  "BVerfGE20180718",
  "ZZV SS 2015 NRW",
  "OstseeSHNSGBefV",
  "BVerfGE20080901",
  "HG 2024/2025 BY",
  "BVerfGE20180410",
  "BVerfGE20120214",
  "BVerfGE20070522",
  "BVerfGE20070727",
  "SHBes\u00dcG SH",
  "DAufsRegelG NRW",
  "Th\u00fcrNRG TH",
  "BVerfGE20090217",
  "BVerfGE20160420",
  "B\u00fcPolBG SH",
  "BVerfGE20201110",
  "GDBNDVerfSchVDV",
  "Th\u00fcrJAG TH",
  "BVerfGE20171010",
  "BVerfGE20160112",
  "BremS\u00dcG HB",
  "HG 2013/2014 BB",
  "MetallTechAusbV",
  "BVerfGE20191119",
  "ZZV SS 2010 NRW",
  "BVerfGE20110125",
  "NaturwMechAusbV",
  "BVerfGE20070720",
  "BVerfGE20120704",
  "BVerfGE20061107",
  "RVBeitrSBek2016",
  "BVerfGE20180321",
  "BVerfGE20140506",
  "HG 2017/2018 BB",
  "BVerfGE20100907",
  "Pr\u00fcfVO NRW",
  "BVerfGE20120124",
  "ChemIndMeistPrV",
  "BVerfGE20180724",
  "BVerfGE20121010",
  "LHG2005/2006 RP",
  "BVerfGE20100129",
  "BVerfGE20171219",
  "VersFinKflAusbV",
  "KostenbeitragsV",
  "BVerfGE20090512",
  "FischWiMeistPrV",
  "BVerfGE20100707",
  "BVerfGE20121219",
  "LStEVSeeSchGBek",
  "HundVerbrEinfVO",
  "HG 2019/2020 BY",
  "BVerfGE20111012",
  "DtBaEntsBeitrBV",
  "Th\u00fcrLWG TH",
  "BVerfGE20151117",
  "Th\u00fcrBhV TH",
  "BZRLPBefugV NRW",
  "BVerfGE20080227",
  "BVerfGE20101012",
  "BVerfGE20080528",
  "BVerfGE20211208",
  "BVerfGE20140401",
  "KonzentratV NRW",
  "BVerfGE20161122",
  "BVerfGE20161222",
  "BMinUWidZustAnO",
  "BVerfGE20080527",
  "BVerfGE20161027",
  "KosmetikerMstrV",
  "BremLMG 2012 HB",
  "Th\u00fcrTGV TH",
  "BVerfGE20091201",
  "HG 2013/2014 HE",
  "BVerfGE20070604",
  "HG 2023/2024 SN",
  "BauStoffPrAusbV",
  "BVerfGE20121106",
  "BVerfGE20080311",
  "HmbS\u00dcGG HH",
  "BVerfGE20200707",
  "BfAAWidVertrAnO",
  "BVerfGE20140226",
  "BayBesG 2001 BY",
  "DPMAWidVertrAnO",
  "BVerfGE20101124",
  "BVerfGE20070320",
  "BVerfGE20130507",
  "Th\u00fcrDSG TH",
  "BVerfGE20081028",
  "BbgArchG1997 BB",
  "Th\u00fcrKAG TH",
  "BVerfGE20140624",
  "RVBeitrSBek2017",
  "BVerfGE20181211",
  "ZZV SS 2016 NRW",
  "DBPDirBeamtRAnO",
  "GemHVO 1991 LSA",
  "GOVerfassGer MV",
  "HG 2008/2009 MV",
  "LandesbankG NRW",
  "IndKfmAusbErprV",
  "BVerfGE20150421",
  "BVerfGE20090804",
  "BVerfGE20060328",
  "BVerfGE20080730",
  "BVerfGE20140723",
  "BVerfGE20090610",
  "BVerfGE20210210",
  "BVerfGE20220426",
  "BVerfGE20200519",
  "BVerfGE20151216",
  "BVerfGE20060215",
  "WinzAusbStEignV",
  "Bln BodSchG Bln",
  "MaschMahnVO NRW",
  "RVBeitrSBek2014",
  "PhilSozSichAbkG",
  "WerkstTerHMstrV",
  "BVerfGE20120504",
  "Nds. AG G 10 NI",
  "BVerfGE20100720",
  "AgrarFachkAusbV",
  "BVerfGE20080703",
  "MilchTechnAusbV",
  "ZZV SS 2018 NRW",
  "MusikFhlErProbV",
  "SeeUnterkunftsV",
  "ZustVOAgrar NRW",
  "DesignStrZV NRW",
  "BVerfGE20121218",
  "ZZV SS 2021 NRW",
  "FertigMechAusbV",
  "GrundWertVO NRW",
  "BVerfGE20141105",
  "BVerfGE20200526",
  "HG 2008/2009 BB",
  "HBeglG 07/08 SN",
  "BVerfGE20070426",
  "S\u00e4chsBO SN",
  "BVerfGE20080213",
  "ZZV SS 2012 NRW",
  "HG 2019/2020 BB",
  "GlasIndMeistPrV",
  "BVerfGE20200527",
  "RVBeitrSBek2006",
  "OGErzeugerOrgDV",
  "BVerfGE20081014",
  "BVerfGE20140114",
  "AG G 10-LSA LSA",
  "Th\u00fcrKWO TH",
  "HmbSeilbahnG HH",
  "ZustVO PStG NRW",
  "BVerfGE20190115",
  "VerfGHGO1995 TH",
  "BVerfGE20170413",
  "ZZV SS 2019 NRW",
  "RVBeitrSBek2010",
  "RingfSchleimKrV",
  "HG 2009/2010 SH",
  "BMWiErnuEntlAnO",
  "BVerfGE20120327",
  "RVBeitrSBek2009",
  "BVerfGE20161206",
  "ZZV SS 2013 NRW",
  "RVBeitrSBek2008",
  "HG 2023/2024 BB",
  "BVerfGE20120725",
  "S\u00e4chsDG SN",
  "BVerfGE20060523",
  "HG 2005/2006 BB",
  "SojaSaatgAnerkV",
  "BMVgWidVertrAnO",
  "BVerfGE20130220",
  "MaschGBEinfV SH",
  "VAPhbD 2016 NRW",
  "ZZV SS 2020 NRW",
  "BVerfGE20140325",
  "MBG Schl.-H. SH",
  "DR\u00c4ndG Bln",
  "HG 2015/2016 BB",
  "UnterlagenBergV",
  "BaumeisterVAblV",
  "BVerfGE20060621",
  "EnergieStG55Bek",
  "BVerfGE20100721",
  "BVerfGE20181218",
  "VersorgAusglBek",
  "BVerfGE20150630",
  "HG 2018/2019 HE",
  "BVerfGE20170919",
  "HessVwVKostO HE",
  "BVerfGE20141007",
  "MiLoGMeldStellV",
  "BVerfGE20210324",
  "RVBeitrSBek2023",
  "TextilProdAusbV",
  "BMJVWidVertrAnO",
  "LStrAusbauG NRW",
  "BVerfGE20110323",
  "BVerfGE20190326",
  "BVerfGE20180530",
  "BVerfGE20170711",
  "BVerfGE20110504",
  "BVerfGE20131217",
  "VwVGBbg 1991 BB",
  "BVerfGE20080610",
  "BVerfGE20170613",
  "BVerfGE20200213",
  "Th\u00fcrKWG TH",
  "BVerfGE20080417",
  "VeranstFachWPrV",
  "BVerfGE20160726",
  "BVerfGE20080115",
  "ZZV SS 2011 NRW",
  "ZZV SS 2022 NRW",
  "BVerfGE20191105",
  "BVerfGE20070927",
  "BVerfGE20090203",
  "BVerfGE20170329",
  "TArztHAusbZustV",
  "AEntGMeldStellV",
  "BVerfGE20180424",
  "FluthilfeOrdErl",
  "StHG 2005/06 BW",
  "AdenauerHStiftG",
  "BVerfGE20080618",
  "Th\u00fcrEBV TH",
  "BVerfGE20090630",
  "VereinZustV NRW",
  "Th\u00fcrGOG TH",
  "ZZV SS 2017 NRW",
  "BVerfGE20080401",
  "RVBeitrSBek2021",
  "BVerfGE20140212",
  "BVerfGE20081111",
  "BVerfGE20130320",
  "BVerfGE20200504",
  "BVerfGE20141119",
  "BVerfGE20060613",
  "BVerfGE20070919",
  "HG 2015/2016 BY",
  "BVerfGE20090507",
  "ZZV SS 2023 NRW",
  "BVerfGE20130305",
  "BVerfGE20110621",
  "BVerfGE20090303",
  "BVerfGE20130219",
  "BVerfGE20061019",
  "Th\u00fcrUKG TH",
  "BVerfGE20091013",
  "BVerfGE20200226",
  "Th\u00fcrGGO TH",
  "MedienGestAusbV",
  "TELEKOMBRErgAnO",
  "BVerfGE20160217",
  "HoheitzeichG MV",
  "BFVwErnuEntlAnO",
  "BMELWidVertrAnO",
  "MarkFachwFortbV",
  "RVBeitrSBek2020",
  "BVerfGE20180514",
  "BVerfGE20170117",
  "ErmittPersV NRW",
  "BVerfGE20171201",
  "BVerfGE20070313",
  "Th\u00fcrLWO TH",
  "BeamtHaftESPBek",
  "ZZV SS 2024 NRW",
  "HG 2011/2012 SH",
  "BVerfGE20091015",
  "BVerfGE20081209",
  "BVerfGE20160215",
  "StuStrRefVO NRW",
  "BVerfGE20150826",
  "ForstWiMeistPrV",
  "BVerfGE20210325",
  "BVerfGE20150512",
  "BVerfGE20200311",
  "BVerfGE20100202",
  "LwErzgSchulproG",
  "MDBNDVerfSchVDV",
  "Th\u00fcrKHG TH",
  "LeasFachwirtPrV",
  "BVerfGE20220209",
  "BVerfGE20070404",
  "MSPTBeihilfeAnO",
  "ZustVKleing NRW",
  "BremVerfSchG HB",
  "BVerfGE20141217",
  "BVerfGE20100706",
  "BVerfGE20150127",
  "BVerfGE20150623",
  "BMVBSDelegatAnO",
  "BVerfGE20150505",
  "Th\u00fcrLMG TH",
  "BVerfGE20211207",
  "Th\u00fcrKGG TH",
  "DigiManKflAusbV",
  "IndElektroAusbV",
  "BremLBO 2018 HB",
  "BVerfGE20130508",
  "HeimsicherungsV",
  "BVerfGE20100414",
  "BrillVerfMAusbV",
  "MetallbildMstrV",
  "BVerfGE20090422",
  "BVerfGE20160926",
  "BVerfGE20120619",
  "BAIUDBwOWiZustV",
  "BVerfGE20200429",
  "ZZV SS 2014 NRW",
  "BVerfGE20200630",
  "BVerfGE20120117",
  "HmbBNatSchAG HH",
  "BVerfGE20220323",
  "WPr\u00fcfG LSA",
  "BVerfGE20120502",
  "Th\u00fcrLHO TH",
  "PrPrTextilAusbV",
  "S\u00e4chsJG SN",
  "CoronaEinreiseV",
  "BVerfGE20071220",
  "S\u00e4chsWG SN",
  "StrKrVerkLeistV",
  "BVerfGE20061206",
  "SondUrlaubG NRW",
  "BMinUBhVZustAnO",
  "FitnessKfmAusbV",
  "SchiffsBelWertV",
  "BVerfGE20120710",
  "BVerfGE20211103",
  "BVerfGE20120207",
  "BVerfGE20160720",
  "BVerfGE20061205",
  "BVerfGE20170523",
  "Th\u00fcrPOG TH",
  "B\u00f6rsVO NRW",
  "BVerfGE20150721",
  "Th\u00fcrMfG TH",
  "BVerfGE20100209",
  "RiBPersVGVO NRW",
  "BVerfGE20070703",
  "GBF\u00fchrV HH",
  "RVBeitrSBek2011",
  "RVBeitrSBek2005",
  "BVerfGE20140115",
  "S\u00e4chsDO SN",
  "EntsorgKTranspG",
  "BVerfGE20051206",
  "Th\u00fcrRKG TH",
  "BbgIngG 2004 BB",
  "WerraSalzGAufhG",
  "BVerfGE20130424",
  "BVerfGE20220628",
  "BVerfGE20060718",
  "BVerfGE20200929",
  "InsoAntrAufschG",
  "ErsatzbaustoffV",
  "StHG 2007/08 BW",
  "PferdewMeistPrV",
  "BVerfGE20220428",
  "BremGVG 1981 HB",
  "BGHWidVertrAnO",
  "Th\u00fcrEG TH",
  "ZollDKlZustAnO",
  "IndElektrAusbV",
  "AdVermiStAnKoV",
  "HdlFachwFortbV",
  "ZVTranspRL NRW",
  "ProdTechnAusbV",
  "BewG55Abs3u4DV",
  "TechnKonfAusbV",
  "MFG Hamburg HH",
  "BbgVerfSchG BB",
  "JudDenkmStiftG",
  "HmbVergabeG HH",
  "BeamtHaftDKBek",
  "BremDSGVOAG HB",
  "Th\u00fcrKO TH",
  "GrundbAutV NRW",
  "RettSchwOrdErl",
  "HmbG10AusfG HH",
  "RVBunduKnBSErG",
  "BbgNatSchAG BB",
  "HmbLVO 1978 HH",
  "BRegEntschBest",
  "AG-SGB XII NRW",
  "LeichtflBAusbV",
  "\u00d6PNVG NRW",
  "Th\u00fcrHG TH",
  "Nds. ArbZVO NI",
  "BVerfGAmtsGehG",
  "WROWiZustV NRW",
  "StaatsHaftG BB",
  "AltLandPflSchV",
  "FHG\u00f6D NRW",
  "OrthVersorgUVV",
  "FachkArbGB Bln",
  "GBAWidVertrAnO",
  "BMFWidVertrAnO",
  "LottStVereinfV",
  "DVO LHundG NRW",
  "ZustVO-KGS NRW",
  "LVwNeuordG LSA",
  "PapIndMeistPrV",
  "ChemSanktionsV",
  "VerfVerInkG MV",
  "DIndBVermVerwG",
  "BDOBuKBMinAAnO",
  "HFeiertagsG HE",
  "ElektroMbMstrV",
  "Fl\u00fcAG NRW",
  "PferdWirtAusbV",
  "BodVerkDUmschV",
  "FundRZustV NRW",
  "EntsorgNHaftpG",
  "ZZV SS2009 NRW",
  "EinlBehPostAnO",
  "SchulversucheV",
  "LAufnG 1996 BB",
  "GesRGenRCOVMVV",
  "WeinTechnAusbV",
  "Nds. FischG NI",
  "BesBek 2011 SH",
  "BbgDSG 2008 BB",
  "BeihBTabak2006",
  "HSchmidtStiftG",
  "MontanMitbestG",
  "StVollstrO NRW",
  "RechtsfachwPrV",
  "PrZBrGleichstV",
  "InstitutsVergV",
  "HZInstrmMAusbV",
  "BPolDKlZustAnO",
  "BayLTGeschO BY",
  "EheschlRWirkgG",
  "PersDLKfmAusbV",
  "KunstHRNRG NRW",
  "Th\u00fcrDG TH",
  "IndFachwirtPrV",
  "MolSozSichAbkG",
  "PolstDekoAusbV",
  "StanzMechAusbV",
  "ImmoDarlSachkV",
  "InflImpfAnsprV",
  "VerstromG3AbwG",
  "BinSchOWiZustV",
  "BeschMechAusbV",
  "BremBodSchG HB",
  "ZZV SS2008 NRW",
  "KonzVO GSR NRW",
  "PersVLehrV NRW",
  "BMIWidVertrAnO",
  "HmbVerfSchG HH",
  "SDschG 2004 SL",
  "NFeiertagsG NI",
  "InfluenzaImpfV",
  "TomSaatgKennzV",
  "RheinSchPersEV",
  "BTVBhHFZustAnO",
  "BeamtHaftNOBek",
  "ForstWiAusbStV",
  "AG AsylbLG NRW",
  "ITSManKflAusbV",
  "BremNatSchG HB",
  "PO-Waldorf NRW",
  "GrAufwEnt10 TH",
  "KfzMechTrAusbV",
  "BfJWidVertrAnO",
  "HundVerbrEinfG",
  "AG SGB XII LSA",
  "Nds. AGInsO NI",
  "TierErzHaVerbG",
  "Th\u00fcrBO TH",
  "MMilchPulvAbsV",
  "TKTransparenzV",
  "HeilBG 1978 RP",
  "OFDSaarbrAufgV",
  "KrWaffUnbrUmgV",
  "HmbRDG 1992 HH",
  "UkrSozSichAbkG",
  "VTMBAProVTFPrV",
  "LederGerbAusbV",
  "SchadRegProtAG",
  "GewinnungsAbfV",
  "AG-BImSchG Bln",
  "BMASWidZustAnO",
  "TiermedFAAusbV",
  "SGBV291FristVV",
  "WvGeflpestMonV",
  "NOKILotsGAusbV",
  "PflSchLuftAnwV",
  "MalerLackAusbV",
  "Nds. AG BMG NI",
  "StBerFAngEignV",
  "VermVerkProspV",
  "UnbilligkeitsV",
  "SteinmetzArbbV",
  "StiftG 2023 SH",
  "Art29VerfG Bln",
  "BekanntmVO NRW",
  "WPr\u00fcfG BB",
  "AlbSozSichAbkG",
  "BMWiWidZustAnO",
  "VerkEHKflAusbV",
  "RSteuZustG NRW",
  "BinSchSprFunkV",
  "St\u00f6rfG NI",
  "VFlughSiKArbbV",
  "MedKfmDigAusbV",
  "GemHVO 1974 RP",
  "2. NHG 2014 BY",
  "BbgS\u00dcG BB",
  "BB-NMitglOG HB",
  "BwBDSGOWiZustV",
  "TierHaltKennzG",
  "DVO BauKaG NRW",
  "AllgVwKostO HE",
  "RollSonnTMstrV",
  "WasserMeistPrV",
  "GrAufwEnt08 TH",
  "StaatshaftG TH",
  "KirchenberufeV",
  "BodSchVereinhG",
  "EuWahlt2014Bek",
  "EuWahlt2009Bek",
  "ArchtG-LSA LSA",
  "NRW.BANK G NRW",
  "\u00d6PNVG LSA",
  "GeldWertArbbV2",
  "VersAnsprReglG",
  "AsylbLGBek2015",
  "UWGEinigStV BB",
  "SchiLichtMstrV",
  "ForstSchAusglG",
  "OfenLufthMstrV",
  "BinSchKapAusbV",
  "MedFAAusbEignV",
  "MaschgefGBV RP",
  "GemHVO 1973 BW",
  "BremArchivG HB",
  "EuWahlt2004Bek",
  "VersAusglKassG",
  "PEhrlInstZustV",
  "VerpflichtG BW",
  "LwK-ProbAV NRW",
  "EdSchleifAusbV",
  "GerStrukGAG MV",
  "Th\u00fcrWG TH",
  "DSchG 1980 NRW",
  "ZuckerMORAufhV",
  "BehWerkPrZustV",
  "WasserstoffNEV",
  "EuWahlt2019Bek",
  "BayRDG 1998 BY",
  "AltersVersErhV",
  "MilchLMeistPrV",
  "BayS\u00dcG BY",
  "GeschO LReg SH",
  "StFachAngAusbV",
  "ZustVO JM NRW",
  "BibuBAProFPrV",
  "MetallbAusbVO",
  "Hess. RAVG HE",
  "KWGFreiStVUSA",
  "GeoTechnAusbV",
  "BbgHG 2014 BB",
  "BeamtVZustAnO",
  "ChirurgMAusbV",
  "ArznMBevV NRW",
  "RindFlSoErstV",
  "MichstAusbGlV",
  "FraktFinzG SL",
  "GemMStrZV NRW",
  "LBesG 1999 BW",
  "BbgArchivG BB",
  "KultgSchKonvG",
  "SubvG-LSA LSA",
  "EthylenoxidVV",
  "WPapBerBeendV",
  "AufwdeckV NRW",
  "LuftVStAnwBek",
  "GoldSchmAusbV",
  "PfandBarwertV",
  "VertrGebErstG",
  "RheinbAusbGlV",
  "HafenLogAusbV",
  "ArchivNGO NRW",
  "TierSeuchAnzV",
  "HilfetelefonG",
  "MilchVerBeihV",
  "TierwMeistPrV",
  "OrthBandMstrV",
  "TELEKOMErnAnO",
  "EpiApoPrOAbwV",
  "KassAufsNeuoV",
  "UmstGeldInstV",
  "TAMMitDurchfV",
  "JVollzMoG NRW",
  "ParkettlMstrV",
  "DVO-BauGB Bln",
  "IMLebensmFPrV",
  "OffshoreBergV",
  "BbgBO 2008 BB",
  "ControllerPrV",
  "HWirtMeistPrV",
  "RHeimstGAufhG",
  "CoronaVMeldeV",
  "BayBG 1998 BY",
  "BremHilfeG HB",
  "\u00d6PNVG BW",
  "FintMechAusbV",
  "SozGerG-AG SL",
  "AbsFondsAuflG",
  "LBesG 2001 MV",
  "KlempnerAusbV",
  "SchadStProtAG",
  "PTStiftErnAnO",
  "ParkettlAusbV",
  "ZuckMLAVAufhV",
  "GO VerfGH Bln",
  "LuftSchlichtV",
  "UntAusschG HB",
  "FleischWArbbV",
  "MTSwEntwAusbV",
  "BezeichnungsV",
  "BannkreisG HH",
  "BKartAZustAnO",
  "GeldStrTV NRW",
  "SeelotRevierV",
  "VolksAbstG SL",
  "SGBXIIRSV Bln",
  "HibHerAusbGlV",
  "BbgNiRSchG BB",
  "FAMaSoFoAusbV",
  "ChirMechMstrV",
  "Hess.AGBGB HE",
  "SeeVersNachwG",
  "JurZulVdV LSA",
  "StBVG NRW NRW",
  "GeflPestAusnV",
  "HmbStPlVVO HH",
  "RechtsberG HB",
  "BPrDGrUnifAnO",
  "RegisterVO SL",
  "TierSchNutztV",
  "GebReinAusbVO",
  "HmbBG 1977 HH",
  "Nds. NiRSG NI",
  "SEIVerfMAusbV",
  "BremStiftG HB",
  "SpurVerkErprG",
  "TerrBekBefrVG",
  "SeeVersNachwV",
  "MilchSonBeihV",
  "ChemFachAusbV",
  "BremImSchG HB",
  "GeldWertArbbV",
  "DaHeSchnMstrV",
  "KlempnerMstrV",
  "FrauenGlG LSA",
  "DenkmalVO NRW",
  "\u00d6PNVG SH",
  "NBrandSchG NI",
  "VergWerkeRegV",
  "BMPTBeamtRAnO",
  "\u00d6GDG NRW",
  "SaarSammlG SL",
  "BGVPTErrichtG",
  "\u00d6PNVG SN",
  "KanalStTarifV",
  "SBesG 1989 SL",
  "BVABesZustAnO",
  "HLeistBVO NRW",
  "KWGFreiStVAus",
  "InfoElekAusbV",
  "JStVollzG NRW",
  "LKAAufgVO NRW",
  "LederFKrAusbV",
  "SEDDiktStiftG",
  "MKWZustVO NRW",
  "GartenKBerPrV",
  "KraftstoffLBV",
  "COVZApprOAbwV",
  "BAKredSitzBek",
  "HolzmechAusbV",
  "FerkBetSachkV",
  "RRefUBeihV MV",
  "JohOrdenNFErl",
  "\u00d6PNVG HE",
  "BayBodSchG BY",
  "GhRentPolAbkG",
  "StromStG10Bek",
  "EnergieStG55B",
  "EURHGAusnahmV",
  "Nds. AGBGB NI",
  "VAP L 2.2 NRW",
  "KiStG-Saar SL",
  "LABG 2002 NRW",
  "SperrWarngebV",
  "MietSchVO NRW",
  "FischEtikettG",
  "BRHWidVertAnO",
  "AGBVormVG NRW",
  "AugenoptAusbV",
  "BayArchivG BY",
  "BayNatSchG BY",
  "BremSeilbG HB",
  "UmSchAnzV NRW",
  "KWGFreiStVJap",
  "GoetheMedStat",
  "ZuVO JuWo NRW",
  "VServiceAusbV",
  "FraktionsG SH",
  "PflVGOWiZustV",
  "AG-SGB II NRW",
  "\u00d6PNVG BB",
  "AMTierhNachwV",
  "AkkStelleGebV",
  "EntsorgFondsG",
  "VersTierMeldV",
  "RDG-ZustV Bln",
  "BS\u00dcG Bln",
  "AG-SGB XII SH",
  "LuftvKflAusbV",
  "ElektroStoffV",
  "FotografMstrV",
  "GtDITZBundVDV",
  "UmstBauSparkV",
  "WaStrGAnlErmV",
  "SaatEinfMeldV",
  "RohstoffStatG",
  "EhrensoldG RP",
  "AG-SGB XII MV",
  "HmbBodSchG HH",
  "ChemGiftInfoV",
  "JVollzDSG NRW",
  "FzgLiefgMeldV",
  "HessAGVwGO HE",
  "MusikFhlAusbV",
  "FHNeuordG NRW",
  "VerfGlasAusbV",
  "FischEtikettV",
  "TouriKfmAusbV",
  "BNDErnuEntlAO",
  "VermFRegG NRW",
  "EWGBauartGenV",
  "InvZulG2005DV",
  "ZweiradFortbV",
  "HessLStatG HE",
  "StaatenlVermG",
  "HHG2004/05 MV",
  "EGGenTDurchfG",
  "BremNiSchG HB",
  "UnivSchlichtV",
  "USAusschG NRW",
  "RettAPrVO NRW",
  "BbgBauGBDG BB",
  "BMinPTDiszAnO",
  "BremSchulG HB",
  "PrLagerhBeihV",
  "HotelMeistPrV",
  "EuRAG-JMV NRW",
  "VisMarkGAusbV",
  "SchSiMeistPrV",
  "PrKultbBDOAnO",
  "ZahntechMstrV",
  "RPflStVtrG SH",
  "EMASPrivilegV",
  "PharmIndMstrV",
  "StatG-LSA LSA",
  "TechKontrollV",
  "Fl\u00fcAG BW",
  "KatSG-LSA LSA",
  "IndMetErprobV",
  "VersLastErstV",
  "SeeEigensichV",
  "KfzUnfEntschV",
  "HBPolVDAufstV",
  "FraktionsG RP",
  "PharmKfmAusbV",
  "LwAusbStEignV",
  "GBPolVDAufstV",
  "PharmRefAusbV",
  "LHauswAusbStV",
  "FeiertagsG HH",
  "KaiserAusbGlV",
  "\u00d6PNVG SL",
  "BbgAbfBodG BB",
  "ProstVerbV SN",
  "\u00d6PNVG MV",
  "DSchG 2012 SH",
  "EdelstGrMstrV",
  "LMinG 1991 MV",
  "BwBeamtAusglG",
  "VolksbDBek TH",
  "ZahntechAusbV",
  "KWGWpIGVermV",
  "STTG 2013 SL",
  "SGB3EntGRuhV",
  "HDSG 1999 HE",
  "FriseurAusbV",
  "PhysLabAusbV",
  "BbgSchulG BB",
  "ProdGewStatG",
  "KoStrukStatG",
  "FStrPrivFinG",
  "WarnowMautHV",
  "SaatArtVerzV",
  "BremLStrG HB",
  "BankFachwPrV",
  "KMilchKennzV",
  "AkkStelleGBV",
  "BForstDKlAnO",
  "InhKontrollV",
  "HanauAusbGlV",
  "MolkMeistPrV",
  "MedFAngAusbV",
  "LS\u00dcG BW",
  "HHG 2024 NRW",
  "LPO 2003 NRW",
  "HeilBerG NRW",
  "ERVkErmV NRW",
  "PersFachkPrV",
  "HygieneV NRW",
  "BMJVBDGRuAnO",
  "BGSResErnAnO",
  "BestattG LSA",
  "FloristAusbV",
  "AVMedKfAusbV",
  "GerZustG Bln",
  "BauGB-AG NRW",
  "KlaCembAusbV",
  "TierpflAusbV",
  "LPresseG LSA",
  "UrlaubsVO SL",
  "DTAGBefugAnO",
  "PflSchadORZV",
  "ElekAnlAusbV",
  "FlugBelWertV",
  "StrReinG NRW",
  "LuftSiSchulV",
  "GVVergVO NRW",
  "RDGZustV NRW",
  "KrGlasKennzG",
  "\u00d6GDG HB",
  "GerStrukG MV",
  "WaffGHZAOWiV",
  "BbgKWahlV BB",
  "KredInstNdlG",
  "LJVwKostG RP",
  "TierSchVersV",
  "MarkschBergV",
  "TerrGewGedTB",
  "SS\u00dcG SL",
  "NVerfSchG NI",
  "HHG 2021 NRW",
  "ZStAVSitzBek",
  "GleichstG HB",
  "WasVersStatV",
  "WinterbeschV",
  "GBmaschV Bln",
  "BremAGBMG HB",
  "S\u00dcG NRW",
  "TaipehStAbkG",
  "GlasappAusbV",
  "SpedKfmAusbV",
  "BayRiStAG BY",
  "UStSchlFestV",
  "AltfahrzeugG",
  "ExpertenratV",
  "KulturGB NRW",
  "VOErmPStA SN",
  "LabChemAusbV",
  "AGSGB XII RP",
  "AusbBerAufhV",
  "PAO157Abs2DV",
  "HessAGFGO HE",
  "GuAMKflAusbV",
  "ImmoKfmAusbV",
  "MetallbAusbV",
  "RaumausMstrV",
  "BewG55Abs8DV",
  "ThAllergeneV",
  "SchriSeMstrV",
  "DruckerAusbV",
  "KiAustrG NRW",
  "SchiedsamtsV",
  "SU-BodAV NRW",
  "GorlebenVSpV",
  "FzgLackAusbV",
  "PPVO 2021 SH",
  "LNatSchG NRW",
  "HadamAusbGlV",
  "TELEKOMBRAnO",
  "S\u00e4HO SN",
  "GOLVerfG LSA",
  "BuchhdlAusbV",
  "BremAbwAG HB",
  "NagoyaProtUG",
  "LRegErmV NRW",
  "KoG-IfSG NRW",
  "EinhBlutArmV",
  "BinSchFondsG",
  "WaffRNeuRegG",
  "\u00d6GDG BW",
  "BayFraktG BY",
  "LGKommRat RP",
  "JArbSchSittV",
  "HwOSchlVerfV",
  "SVVollzG NRW",
  "MeistPrFRGlV",
  "UmwStGAusnVV",
  "UmlageVO NRW",
  "WahlKostG SL",
  "FwSozwFortbV",
  "BbgLWahlV BB",
  "RAVG NRW NRW",
  "HHG 2020 NRW",
  "LVerfSchG SH",
  "GesamtBeitrV",
  "AusglFoTilgG",
  "COVAAppOAbwV",
  "VO-DV II NRW",
  "BbgKWahlG BB",
  "BezVerwG Bln",
  "GesBerAusbSV",
  "FABaumPflPrV",
  "AGMahnVordrV",
  "DrechslAusbV",
  "VwZG-LSA LSA",
  "HHG 2018 NRW",
  "LVerfSchG MV",
  "FriseurArbbV",
  "SchwPestMonV",
  "EGBlauzBekDV",
  "HAGArt10G HE",
  "SportFMAusbV",
  "TierpflMstrV",
  "FSMusterzulV",
  "BauwAbdAusbV",
  "FrHfBremhGrV",
  "FachvLMAusbV",
  "LBodSchG NRW",
  "NOKWeichBefV",
  "NSUnrUrtBesG",
  "InfoGesStatG",
  "LS\u00dcG SH",
  "MetallbMstrV",
  "HHG 2022 NRW",
  "LSchuldbG RP",
  "TourKfmAusbV",
  "ForstWiAusbV",
  "TextLabAusbV",
  "IndMstrAusbV",
  "SHBeamtVG SH",
  "EHdlFwFortbV",
  "WZuckerBeihV",
  "BMinJDiszAnO",
  "ImmoFachWPrV",
  "DBiblBDODAnO",
  "PflSchSachkV",
  "StichprobenV",
  "HZG 2008 NRW",
  "ARVZustV NRW",
  "BMFamZustAnO",
  "SpkG-LSA LSA",
  "EWGFinBeistG",
  "RiFlEtikettG",
  "BestattAusbV",
  "BayImSchG BY",
  "KfzTechMstrV",
  "NLVO 2001 NI",
  "HHG 2016 NRW",
  "VermKatG NRW",
  "StVZustV NRW",
  "LVerfSchG RP",
  "JuZwAnwG LSA",
  "GDSG NRW NRW",
  "KfzServAusbV",
  "FahrschAusbO",
  "RestMeistPrV",
  "WeinAlkoAbsV",
  "XBasisdatenV",
  "GeringFordVO",
  "BKWidZustAnO",
  "IndElErprobV",
  "ZqualBLV NRW",
  "HmbArchtG HH",
  "HygMedVO NRW",
  "ChemVOCFarbV",
  "BetonFBAusbV",
  "ZVO-IfSG NRW",
  "EComKflAusbV",
  "DBPDirErnAnO",
  "EigBetrVO NI",
  "UntAusLTG BY",
  "BVSG NRW NRW",
  "HAltPflHG HE",
  "EuMahnverfVO",
  "OFDBremAufgV",
  "GntVDDVCSVDV",
  "ZuckProdAbgV",
  "BrennMstrLwV",
  "SGZDVertrAnO",
  "FDAG NRW NRW",
  "BremWahlG HB",
  "FlechtwAusbV",
  "ZMediatAusbV",
  "DPAGBefugAnO",
  "DrogenkV NRW",
  "BbgLWahlG BB",
  "VerfGHGO NRW",
  "HLPG 2002 HE",
  "LeuchtrAusbV",
  "PersFWFortbV",
  "IfSGMeldPflV",
  "ChemVerbotsV",
  "HHG 2017 NRW",
  "LasthandhabV",
  "OrthSchMstrV",
  "TelekomBATZV",
  "BeitrEntlKrG",
  "WaffGDVO NRW",
  "KEPFachAusbV",
  "BbgMeldeG BB",
  "SchaumwZwStV",
  "SchaumwZwStG",
  "PfandBrAUmwG",
  "SaarlGebG SL",
  "FachHwirtPrV",
  "DrogistAusbV",
  "BankkflAusbV",
  "SoldRehaHomG",
  "RiLPVGVO NRW",
  "VersStaatsVG",
  "SLPG 2002 SL",
  "RD-ZustV NRW",
  "BMFSVZustAnO",
  "ZwrMechMstrV",
  "StVollzVergO",
  "BAFzAZustAnO",
  "ArbMaFAAusbV",
  "ReiseSFEntgV",
  "TextilKennzG",
  "WSVZuAnpErmG",
  "AGSGB XII BW",
  "BremVwVfG HB",
  "\u00d6GDG MV",
  "IsolierAusbV",
  "WinzMeistPrV",
  "StSchuBuG SN",
  "LPflegEG Bln",
  "VergoldAusbV",
  "BFStrSonGebV",
  "KfmMKomAusbV",
  "ReNoPatAusbV",
  "ZweiradAusbV",
  "SportSeeSchV",
  "ArchIngKG SH",
  "SeeArbEinrFV",
  "KlauenPflPrV",
  "AGSGB XII SL",
  "BVABundFamkV",
  "HaagUrkBefrV",
  "HmbBeihVO HH",
  "LKHG 2002 MV",
  "GoetheMedStE",
  "KartASitzBek",
  "BinSchAbgasV",
  "StiftGBbg BB",
  "SVerfSchG SL",
  "LS\u00dcG RP",
  "IndMetMeistV",
  "WPapBerSchlG",
  "PrHaushStatG",
  "HeimMindBauV",
  "ArchG1989 RP",
  "L\u00d6G NRW",
  "BruteiKennzV",
  "TierSeuchErV",
  "BerlStrG Bln",
  "AnpflEigentG",
  "APO-GOSt NRW",
  "ProzManAusbV",
  "HHG 2023 NRW",
  "BlnAGBMG Bln",
  "VerwGebVO SH",
  "AuslKfzHPflV",
  "FinV MRV NRW",
  "LBG 2003 Bln",
  "KrWaffKontrG",
  "UniBwLeistBV",
  "EltBauVO NRW",
  "OFDHambAufgV",
  "SterilEAufhG",
  "EinigStV NRW",
  "VerkVereinfG",
  "ErmPStAV LSA",
  "BVO 1975 NRW",
  "BremDSchG HB",
  "JAVollzG NRW",
  "BbgFischG BB",
  "EntschVO NRW",
  "VerkKfmAusbV",
  "ZahnmedAusbV",
  "HKHG 2011 HE",
  "AG-SGB II MV",
  "GemKHBVO NRW",
  "BremArchG HB",
  "HausO LT LSA",
  "APOGV1991 SN",
  "SteinkohleFG",
  "LBodSchAG BW",
  "StrafAktEinV",
  "BRegAmtsWhgV",
  "UnbBeschErtV",
  "DPMAEinstAnO",
  "PKBaSSatzung",
  "BMinVgErnAnO",
  "AutoKflAusbV",
  "FloristMFPrV",
  "AGSGBVIII SN",
  "GrHessenNRWB",
  "\u00d6GdG RP",
  "HHG 2019 NRW",
  "NagProtBGebV",
  "EEZV-LRH NRW",
  "SchV-KHG NRW",
  "RohrMeistPrV",
  "BremWaldG HB",
  "ChemBiozidDV",
  "BMinUZustAnO",
  "RiFlEtikettV",
  "BfArMZustAnO",
  "VermittVergV",
  "StVollzG NRW",
  "MinisterG RP",
  "UVBKostErstV",
  "VwVfGBln Bln",
  "BEStrafAktEV",
  "UmzServAusbV",
  "B\u00fcWG HH",
  "EnSiGEntschV",
  "VerfGGBbg BB",
  "AltfahrzeugV",
  "BekanntVO SH",
  "BehAppbAusbV",
  "PsychThApprO",
  "DlKonjStatG",
  "NatSchG Bln",
  "LHG 2022 RP",
  "BremAbgG HB",
  "BbgSchGG BB",
  "ErwerbStatV",
  "BNetzABGebV",
  "LBG 1998 MV",
  "MikrotAusbV",
  "FeiertG Bln",
  "AltPflG-NRW",
  "BDGBMinGAnO",
  "StrRehaHomG",
  "ZustAVO NRW",
  "BMJVertrAnO",
  "StruktHFGAG",
  "EdlStFAusbV",
  "KunstHG NRW",
  "LBO 2000 SH",
  "BremAZVO HB",
  "HochhVO NRW",
  "APO-S I NRW",
  "ArchIngG MV",
  "FinaRisikoV",
  "SiSchmAusbV",
  "HVwKostG HE",
  "FinDAGKostV",
  "RDG 1993 MV",
  "BEPNStruktG",
  "BayStrAG BY",
  "AugOptMstrV",
  "FrSaftAusbV",
  "BW AGBMG BW",
  "HmbArchG HH",
  "EndlagerVlV",
  "KohleMeldeG",
  "BestattG BW",
  "BedGewV NRW",
  "PatInfoZBek",
  "BwFahnenAnO",
  "BinSchStrEV",
  "RDGZustV HB",
  "HAGFamFG HE",
  "StrbauMstrV",
  "TreuhUmbenV",
  "SeeLotsEigV",
  "G10AGBbg BB",
  "BNichtrSchG",
  "KonsVerFRAV",
  "BranntwMonG",
  "BauGebVO MV",
  "PolKostV SL",
  "KomBesVO SH",
  "ObstGemMODV",
  "HG 2013 NRW",
  "BbgRettG BB",
  "S\u00dcG MV",
  "BRSekrHausO",
  "ModistAusbV",
  "KerIndAusbV",
  "GnO NRW NRW",
  "LAVO IT.NRW",
  "MPorzMAusbV",
  "WahlBewCovV",
  "KAG-LSA LSA",
  "JVAmtZVerlG",
  "HochSchG RP",
  "UAusschG SN",
  "FMSASatzung",
  "SeeBewachDV",
  "StrWG-MV MV",
  "BmTierSSchV",
  "EigJapV NRW",
  "HessVwZG HE",
  "HeilBerG BB",
  "HeizkZuschG",
  "BauPAVO NRW",
  "BayVersG BY",
  "LNatSchG SH",
  "HG 2015 NRW",
  "BayWaldG BY",
  "VwKostG LSA",
  "VerfGHGO RP",
  "SiebdrMstrV",
  "FahrlAusbVO",
  "PauschV NRW",
  "HymneBriefB",
  "WODrittelbG",
  "WachszMstrV",
  "LBG 2005 SH",
  "OrthoptAPrV",
  "SchuhmMstrV",
  "PostbankSZV",
  "FHKBeauftrV",
  "BodenlAusbV",
  "FamZuwV NRW",
  "HmbGleiG HH",
  "LHG 2021 RP",
  "BiZeitG Bln",
  "AVwGebO NRW",
  "VerfGHGO TH",
  "PresseG Bln",
  "StVWasAusbV",
  "CoronaImpfV",
  "AltGZustAnO",
  "LPflegeG BB",
  "EWKVerbotsV",
  "BbgBestG BB",
  "EntgTranspG",
  "BRegSitzBek",
  "ArchivG NRW",
  "BbgJagdG BB",
  "MntZollDVDV",
  "FeiertG LSA",
  "EishAusbErV",
  "NBodSchG NI",
  "LEisenbG BW",
  "HG 2008 NRW",
  "VO VwVG NRW",
  "GntZollDVDV",
  "AltPflG NRW",
  "HeilBerG HB",
  "HG 2019 LSA",
  "KraftStCHEV",
  "StromStG10B",
  "TierImpfStV",
  "KfzServTPrV",
  "AuswVfG NRW",
  "RDGZustV RP",
  "LArchivG MV",
  "LFischG NRW",
  "SchAusnahmV",
  "HessVwVG HE",
  "BesStZpBetV",
  "MedienG LSA",
  "SeeArbEinrV",
  "TierSoBeihV",
  "HG 2004 NRW",
  "HArchivG HE",
  "LbV 1996 BY",
  "KonsVerBELV",
  "UVBErrichtG",
  "SNG 1993 SL",
  "LbV 2009 BY",
  "BrucelloseV",
  "VgG 2002 HB",
  "KonsVerLUXV",
  "ArbZustBauV",
  "TSEVorsorgV",
  "BaFinBefugV",
  "StVUnfStatG",
  "LeistBeschV",
  "FZulGAnwBek",
  "SchHaltHygV",
  "LuftSpZustV",
  "BestattG SH",
  "LBG 1999 BB",
  "NPflegeG NI",
  "VAbstVO LSA",
  "GO-RefG NRW",
  "BlindKennzV",
  "NPNordSBefV",
  "LFischG Bln",
  "KonsVerNLDV",
  "NHG 2020 SH",
  "HmbKatSG HH",
  "SGBIIKennzV",
  "SeeUmwVerhV",
  "BMJFGErnAnO",
  "HG 2010 NRW",
  "LeichenG HB",
  "HmbAGGVG HH",
  "BABauRaumOG",
  "HG 2012 NRW",
  "HolzblMstrV",
  "DPMAVwKostV",
  "ProManElPrV",
  "KindArbSchV",
  "ESWettbV HH",
  "BbgArchG BB",
  "GastroAusbV",
  "JugendBildG",
  "LPflegeG SH",
  "AG-BauGB MV",
  "LHG 2016 RP",
  "RSpkAPO NRW",
  "FESchVO NRW",
  "ZuwArbStatV",
  "EltBauVO SH",
  "ArbZAbsichG",
  "IndKfmAusbV",
  "FHVOPol NRW",
  "BaFinHwgebV",
  "SpielbG NRW",
  "EbertStiftG",
  "LaFamKaV HB",
  "LEnteigG RP",
  "AbgGRhPf RP",
  "NNatSchG NI",
  "BaySchlG BY",
  "ChancenG BW",
  "BVollzVergV",
  "HolzbhAusbV",
  "LMedienG BW",
  "RechtUBV SL",
  "FuttMKontrV",
  "KDVErstattV",
  "VO-DV I NRW",
  "PsychKG NRW",
  "HmbJagdG HH",
  "UmglVGH NRW",
  "AgrarAbsFDG",
  "KonsVerUSAV",
  "KomAbwV NRW",
  "HG 2014 NRW",
  "AkGradV NRW",
  "BauGB-AV HE",
  "WahlkostenV",
  "BbgLeBiG BB",
  "KflDGVAusbV",
  "EntschG LSA",
  "BaySchFG BY",
  "GlasblAusbV",
  "BBiGZustAnO",
  "APO-WbK NRW",
  "WTG DVO NRW",
  "BbgSchlG BB",
  "InvestAusbV",
  "FrHfHHAufhG",
  "EpLaFoBTBek",
  "KonsVerCHEV",
  "TischlMstrV",
  "BerlAVG Bln",
  "EinigStV NI",
  "LAGPflB NRW",
  "GlaserMstrV",
  "LPflegeG MV",
  "RDGZustV BY",
  "LImschG NRW",
  "BayStrWG BY",
  "BayDSchG BY",
  "HessAbgG HE",
  "PostBetrZuV",
  "WOMitbestEG",
  "AusglLeistG",
  "BremUVPG HB",
  "HmbSubvG HH",
  "WeinRAufrEV",
  "BootsbMstrV",
  "GerOrgG LSA",
  "TelekomJubV",
  "AuslZuschlV",
  "GGKontrollV",
  "APO VFA NRW",
  "BMWiBDGDAnO",
  "HeizkostenV",
  "VersFaWiPrV",
  "TKrMeldpflV",
  "MitbestBeiG",
  "UVollzG NRW",
  "KiStGDV NRW",
  "BbgKVerf BB",
  "BestattG NI",
  "MinRohSorgG",
  "MaxPlanckGM",
  "MediationsG",
  "PersAnpassG",
  "TischlAusbV",
  "GGArt115dGO",
  "FischSeuchV",
  "VerwBehG HH",
  "LEisenbG RP",
  "HmbAGBMG HH",
  "BlnMobG Bln",
  "HgFSNatSchV",
  "BayStatG BY",
  "LVerfGG LSA",
  "FeiertG NRW",
  "BinSchArbZV",
  "ResOG SH SH",
  "HPresseG HE",
  "VerfGHG NRW",
  "VIVBVEG NRW",
  "BMWiTWidAnO",
  "KassenSichV",
  "LBodSchG SH",
  "ArbGErrG BB",
  "BVerfGZustB",
  "BestattG SL",
  "InsoGEinzKV",
  "HG 2023 LSA",
  "GrBremenNIB",
  "SchKfmAusbV",
  "PanDStVAbkG",
  "LRiStaG NRW",
  "SignBenennV",
  "LEisenbG SH",
  "AGSGB II RP",
  "ArbGOrgG BY",
  "KOVRentKapG",
  "HmbPSchG HH",
  "LEisenbG SN",
  "VwFAngAusbV",
  "BremVwVG HB",
  "LSeilbG Bln",
  "BMinGSBRAnO",
  "BayHSchG BY",
  "HafensAusbV",
  "HolzbhMstrV",
  "HeilBerG MV",
  "BremKrhG HB",
  "HoheitsG SH",
  "GAPInVeKoSG",
  "WoBerichtsG",
  "NatSchAG MV",
  "MMilchPulvV",
  "BTBerlinBek",
  "IOrgRentenG",
  "KEPKfmAusbV",
  "MilchQZustV",
  "SanOAAusbGV",
  "AG InsO NRW",
  "BeherbStatG",
  "VertretG SL",
  "DachdArbbV9",
  "BBeitrBesch",
  "JurAusbRefG",
  "NVVergVO NI",
  "BMinUWidAnO",
  "BremNatG HB",
  "BootsbAusbV",
  "AZVOPol NRW",
  "KartGBV NRW",
  "FKeramAusbV",
  "DatAustUSAG",
  "BinSchAusbV",
  "HG 2007 NRW",
  "BuTMedAusbV",
  "BremPolG HB",
  "BbgAGBGB BB",
  "BMGSZustAnO",
  "JVKostG Bln",
  "SiebdrAusbV",
  "TierSchKomV",
  "NBG 2001 NI",
  "HG 2014 LSA",
  "RennwLottDV",
  "BeherbMeldV",
  "IndMetAusbV",
  "SchSiSAusbV",
  "StmStbAusbV",
  "BinSchAufgG",
  "UAusschG HH",
  "BlauzungenV",
  "FremdSprPrV",
  "TabakBlSchV",
  "AG InsO LSA",
  "WoZustV NRW",
  "HG 2011 NRW",
  "EUFinSchStG",
  "HmbStatG HH",
  "BergWoZErhV",
  "PflBeschauV",
  "HmbKiStG HH",
  "APG DVO NRW",
  "KHSt-VO NRW",
  "HmbRpflG HH",
  "NPresseG NI",
  "DGJugdwAbkV",
  "VersStaatsV",
  "BBiGZustBek",
  "WinzerAusbV",
  "LKreiWiG BW",
  "GBRegVO LSA",
  "RegZensErpG",
  "SchuldRAnpG",
  "HG 2024 LSA",
  "BremVwZG HB",
  "AG VwGO LSA",
  "AbfBeauftrV",
  "KonsVerAUTV",
  "HAbg-VO NRW",
  "KonsVerGBRV",
  "LuftRAAbkDG",
  "PfandMeldeV",
  "WO-LPVG NRW",
  "GKG-LSA LSA",
  "MaschGBV BB",
  "SegelmMstrV",
  "PflegeStatV",
  "MaschGBV TH",
  "SeilbDGGebV",
  "HG 2022 LSA",
  "AARKZustAnO",
  "MFG 2003 SH",
  "DBBeamtRAnO",
  "VSchwKrSchV",
  "FrakRStG SN",
  "SchuldBBerG",
  "BMVgBDODAnO",
  "ArbUnfStatV",
  "LSchuWG NRW",
  "FzMechAusbV",
  "DirektVAbkV",
  "DemoGStErrG",
  "BioMatHintV",
  "NVwKostG NI",
  "VwVfGBbg BB",
  "BinSchPersV",
  "SchuhfAusbV",
  "SchSiFAusbV",
  "SchwarmfdPV",
  "BremEntG HB",
  "VO MRVG NRW",
  "BNotOAV NRW",
  "HmbVwVfG HH",
  "RebflAnpflV",
  "BwFinSVermG",
  "BbgDSchG BB",
  "MilchLAusbV",
  "EGRebflRodV",
  "FischVermNV",
  "HafenVSG HH",
  "MeistAnerkV",
  "BremIngG HB",
  "SchlussFinG",
  "BestattG MV",
  "VerfGHG Bln",
  "FreiwFortbV",
  "AEV BBM NRW",
  "UAGOWiZustV",
  "SchwarzArbG",
  "EnteigG LSA",
  "BefBezBG RP",
  "TRubelVerjG",
  "AbgrabG NRW",
  "SVFAngAusbV",
  "BehAppMstrV",
  "FischwAusbV",
  "BbgStatG BB",
  "ThermMAusbV",
  "JurPrNotenV",
  "LPresseG SH",
  "LuftVerkSiV",
  "StmStbMstrV",
  "HessNRSG HE",
  "FeuerschStG",
  "BbgKiStG BB",
  "PolVBDVorgV",
  "CO2KostAufG",
  "BayVwVfG BY",
  "BStrafAktFV",
  "NMedienG NI",
  "HG 2009 NRW",
  "NachbarG SL",
  "AGBauGB Bln",
  "KraftFArbZG",
  "LHG 2011 RP",
  "WapFlagG RP",
  "AG-KJHG NRW",
  "EingrVO NRW",
  "FeuerbrandV",
  "LNatSchG RP",
  "SachenRBerG",
  "KomKBVO LSA",
  "BbgMinG BB",
  "MahnVordrV",
  "BrennAusbV",
  "BienSeuchV",
  "KWahlG NRW",
  "MPAHSBundV",
  "EigAnVO RP",
  "HG 2022 BB",
  "ApoAnwRstG",
  "LFischG RP",
  "GasHDrLtgV",
  "BDBOSZertV",
  "GemKVO NRW",
  "GlasVAusbV",
  "PfleDatEAV",
  "LStatG NRW",
  "HG 2012 BB",
  "EVerbrStBV",
  "LuftSiGebV",
  "FrhfnAufhG",
  "GBPolVDVDV",
  "SenatsG HB",
  "SLStatG SL",
  "SenatsG HH",
  "SonntVerkV",
  "HG 2010 HE",
  "AtEntsorgG",
  "PostSchliV",
  "BeamtVG SH",
  "HG 2021 BY",
  "UVKapWertV",
  "HG 2021 SH",
  "WeinfondsV",
  "ArmDStAbkG",
  "LFBRVG NRW",
  "HG 2021 HE",
  "FrUrlV NRW",
  "FlurbGG HH",
  "KorbmMstrV",
  "JAbschlWUV",
  "SHKAMAusbV",
  "LPflGG Bln",
  "JAPrVO LSA",
  "ErholNutzG",
  "StuckMstrV",
  "AGVwGO Bln",
  "VorVfG NRW",
  "BBhZustAnO",
  "HG 2015 SH",
  "HG 2015 HE",
  "BuchbAusbV",
  "MBPolVDVDV",
  "SchulG Bln",
  "ThermMstrV",
  "RefoKiVtgG",
  "CoronaSchV",
  "HessBGG HE",
  "LJagdG Bln",
  "HG 2011 SL",
  "UntAbschlG",
  "SichLVFinV",
  "LSeilbG SH",
  "KfzStVertG",
  "BbgVwGG BB",
  "BABWismarG",
  "EnergieStG",
  "PersVG Bln",
  "BMGSWidAnO",
  "GasGKErstV",
  "FKrFBAusbV",
  "BMABGDDAnO",
  "KSKBeiratV",
  "GebGBbg BB",
  "AbschlagsV",
  "TextRMstrV",
  "PresseratG",
  "LVOPol NRW",
  "BRAOAV NRW",
  "AlkopopStV",
  "DGBankUmwG",
  "BMVgBDGAnO",
  "EigenVerbV",
  "BfEZustAnO",
  "BRHSitzBek",
  "GerOrgG HE",
  "NachbG NRW",
  "NWaldLG NI",
  "HmbIngG HH",
  "LbPrZGlStV",
  "FMontAusbV",
  "LJagdG LSA",
  "HotelAusbV",
  "FraktG Bln",
  "HG 2023 BY",
  "SoEnergieV",
  "GlAppMstrV",
  "StiftG Bln",
  "LPressG BW",
  "MilchQuotV",
  "WeinASachV",
  "PBefAusglV",
  "GlasVMstrV",
  "VolksEG HB",
  "EUSozSichG",
  "HG 2017 SH",
  "WappenG SN",
  "PelzVAusbV",
  "MISSAufstV",
  "BbgUVPG BB",
  "RVBedWohnV",
  "EnteigG SH",
  "EuRatWahlG",
  "SchauAusnV",
  "EnteigG SL",
  "BbgLSBG BB",
  "BKMZustAnO",
  "ReifKennzV",
  "BremEBG HB",
  "ArchGB Bln",
  "BesStruktG",
  "BerlHG Bln",
  "LWLogAusbV",
  "EUGewSchVG",
  "LJKostG BY",
  "VerbrVerbG",
  "LFischG MV",
  "HG 2018 SH",
  "AZV Bbg BB",
  "BbgPolG BB",
  "OrgHbMstrV",
  "VerfGHG SL",
  "HdlDlStatG",
  "GleichberG",
  "BremFiG HB",
  "InvZulBerG",
  "LImschG BB",
  "BayVwSG BY",
  "LSubvG NRW",
  "AbgG SL SL",
  "RaumAAusbV",
  "HmbUVPG HH",
  "AVBWasserV",
  "HmbVwVG HH",
  "EGEntschRG",
  "SammlungsG",
  "LWahlG NRW",
  "GVVergV HE",
  "NStiftG NI",
  "WoGenVermG",
  "UStGemAntV",
  "PersVG LSA",
  "NRettDG NI",
  "JAbschlVUV",
  "VersAusglG",
  "LFischG SH",
  "BeitrEntlG",
  "NVAbstG NI",
  "FischG LSA",
  "SBauVO NRW",
  "AujeszkKrV",
  "VereinsGDV",
  "WDErstattV",
  "SozSichUKG",
  "AG G 10 TH",
  "LWahlG Bln",
  "HmbSfTG HH",
  "SVDDRAuflG",
  "3. AG-KJHG",
  "UStatEntlV",
  "GtDBahnVDV",
  "PresseG HH",
  "APO-OS NRW",
  "PflSchAnwV",
  "LSchliG SH",
  "GerOrgG BY",
  "AuslWoBauG",
  "WeinkMstrV",
  "LRiStAG BW",
  "HG 2011 HE",
  "HG 2016 HE",
  "NachbG Bln",
  "ArbZVO LSA",
  "GlasmAusbV",
  "MuSchSoldV",
  "SVFwAnerkV",
  "EGTSEAusnV",
  "HG 2022 SH",
  "LStatG Bln",
  "BremBGG HB",
  "HG 2021 BB",
  "BGSBDODAnO",
  "LStiftG RP",
  "MntDBwVVDV",
  "GerOrgG RP",
  "JugendarbG",
  "GemKVO LSA",
  "NiSchG NRW",
  "AG BGB NRW",
  "JKostG LSA",
  "NArchtG NI",
  "StiftG NRW",
  "PolstAusbV",
  "BbgBesG BB",
  "LPersVG RP",
  "BayLplG BY",
  "WertAusglG",
  "HufBeschlV",
  "SortSchBek",
  "HSGArtG SH",
  "AGInsO Bln",
  "TierSchTrV",
  "FrHfCuxGrV",
  "SFischG SL",
  "MedaillenV",
  "RiGBln Bln",
  "VerkFlBerG",
  "VerfRAG SN",
  "MSchnAusbV",
  "BremLWO HB",
  "LSeilbG RP",
  "HwKDAbrufV",
  "TWirtAusbV",
  "FraktG LSA",
  "MilchSoPrG",
  "OZGPortalV",
  "AbgAnpAusG",
  "SH AbgG SH",
  "SeilbG NRW",
  "TouriFwPrV",
  "PackmAusbV",
  "AutomAusbV",
  "WoStichPrG",
  "GeigbMstrV",
  "KVMeistPrV",
  "HBeihVO HE",
  "HufBeschlG",
  "BbgStrG BB",
  "BremBZG HB",
  "BFinHSHuaG",
  "BerlBG Bln",
  "RAZEignPrV",
  "LVerbO NRW",
  "KrStBV NRW",
  "HStiftG HE",
  "ZOVersDTAG",
  "LSeilbG BW",
  "HG 2024 SH",
  "StrVerjFrG",
  "BrauMMstrV",
  "PrKultbSaV",
  "BStrMKnotV",
  "ZinsVAufhV",
  "MilchFettG",
  "LWahlO NRW",
  "RbGeldERAV",
  "SPersVG SL",
  "SchAnpGBek",
  "KomHVO NRW",
  "HWoAufG HE",
  "LHundG NRW",
  "LandwArbbV",
  "HmbNSGBefV",
  "JHiStruktV",
  "LogMstrFbV",
  "HmbBesG HH",
  "BayAbfG BY",
  "TranspRLDV",
  "BuchBMstrV",
  "SchulG LSA",
  "GrPfREuroV",
  "TelekomSZV",
  "FraktG NRW",
  "AkkStelleG",
  "KatSchErwG",
  "HandzMstrV",
  "StPVLVO RP",
  "IntKonnBek",
  "HG 2019 SH",
  "FeinwAusbV",
  "HomTAMRegV",
  "PreisStatG",
  "BismStiftG",
  "FilmDigitV",
  "HtDBWVAPrV",
  "KrWaffGenV",
  "APO-BK NRW",
  "NNachbG NI",
  "GfwtDBwVDV",
  "ERVV Ju BY",
  "VersResAbV",
  "VBegVEG HE",
  "SchulG NRW",
  "WrackBesDG",
  "HG 2010 BB",
  "VwKostG MV",
  "BauFordSiG",
  "HG 2017 HE",
  "RdfunkG HE",
  "HmbVwZG HH",
  "HG 2022 BY",
  "WassBMstrV",
  "HG 2016 SH",
  "WohnortPEG",
  "BEBeamtAnO",
  "TelekomAZV",
  "BDGBaFinDV",
  "HG 2014 SH",
  "PostLEntgV",
  "BMeldDigiV",
  "AGArbGG HE",
  "VtgHENIBek",
  "PostPersRG",
  "DPMAErnAnO",
  "GemFinRefG",
  "SeeSpbootV",
  "BayGMPP BY",
  "GBWiederhV",
  "HFischG HE",
  "PTUKErnAnO",
  "BayAbgG BY",
  "HmbGfGG HH",
  "HG 2023 SH",
  "BAStrlSchG",
  "FahrmAusbV",
  "EinglMindV",
  "MuSchEltZV",
  "BBankPersV",
  "TierSchHuV",
  "ESchVO NRW",
  "VersFG Bln",
  "FA-ZVO NRW",
  "DarlehensV",
  "BMG-AG LSA",
  "HmbAbfG HH",
  "RennwLottG",
  "WoVermittG",
  "KiSteuG HE",
  "LWaldG LSA",
  "PBefGKostV",
  "KomHKVO NI",
  "PCBAbfallV",
  "VergStatVO",
  "ERPEntwHiG",
  "PresseG HB",
  "HDiszErstV",
  "AlkopopStG",
  "VAbstG LSA",
  "VerfGHG BW",
  "FrHAblErgG",
  "HG 2011 BB",
  "IndMIsoPrV",
  "LBesGBW BW",
  "GenBeschlG",
  "MPBetreibV",
  "HG 2022 HE",
  "DonauSchPV",
  "ArbREGAnpG",
  "HG 2020 HE",
  "WissZeitVG",
  "KWahlO NRW",
  "BremSVG HB",
  "HmbFAnG HH",
  "MilchMargG",
  "LImSchG RP",
  "BLESitzBek",
  "SchuVAbdrV",
  "KomHVO LSA",
  "FeinOAusbV",
  "LPersVG BB",
  "DBATRNotiV",
  "WBOZustAnO",
  "TEKGFRL HB",
  "BWappenBek",
  "LNRSchG BW",
  "JFAngAusbV",
  "BbgKHEG BB",
  "ProstStatV",
  "BremKEG HB",
  "WpHGMaAnzV",
  "FHBLeistBV",
  "ElekZeugnV",
  "HKrimDAPrV",
  "MetblMstrV",
  "KlimaBergV",
  "BUKDiszAnO",
  "SeeVerkSiV",
  "BEVSitzBek",
  "EpLaFoBek3",
  "PachtkredG",
  "LEntwG LSA",
  "EigBGes HE",
  "FinStabDEV",
  "PlVereinfG",
  "ERPWPG2009",
  "SchStG LSA",
  "KlaCbMstrV",
  "DHPolG NRW",
  "SVFwFortbV",
  "BVASitzBek",
  "BMGSErnAnO",
  "BWHWFortbV",
  "MietRVerbG",
  "SeeBewachV",
  "PatAnwAPrV",
  "EntschFinV",
  "LSeilbG MV",
  "PharmAusbV",
  "VermVerMiV",
  "GntDBwVVDV",
  "OrthAusbVO",
  "AG-TPG NRW",
  "BMASErnAnO",
  "EndlSiAnfV",
  "BBHZVO NRW",
  "VerfGHG RP",
  "BauWiAusbV",
  "BergMAusbV",
  "VersMeldeV",
  "StromBGebV",
  "NPersVG NI",
  "FSOWiZustV",
  "BbgVwZG BB",
  "DirektWGGB",
  "HG 2005 HE",
  "UrhGBefStV",
  "GtDBWVAPrV",
  "KommHVO SL",
  "EntGBbg BB",
  "LWaldG Bln",
  "FStatAusnV",
  "DachdMstrV",
  "HG 2013 SH",
  "BremBVO HB",
  "BWKennzAnO",
  "FSchVO Bln",
  "SodEGVerlV",
  "BremRiG HB",
  "HG 2024 NI",
  "LVerfGG MV",
  "BDGBMASKDV",
  "AGBauGB SH",
  "HG 2020 SH",
  "PersEinspG",
  "GntDAIVVDV",
  "SeeSchStrO",
  "HmbAbwG HH",
  "RettDG LSA",
  "AG G 10 MV",
  "HG 2012 HE",
  "KartKrebsV",
  "BauArbbV10",
  "AG SGG LSA",
  "GemHVO NRW",
  "BayLaBG BY",
  "BlnDSG Bln",
  "BremLVO HB",
  "LSeilbG SN",
  "SchUnfDatG",
  "StiftG LSA",
  "KeramMstrV",
  "BayMinG BY",
  "LastAbschV",
  "WidZustAnO",
  "StrVerkSiV",
  "SeilbG LSA",
  "EnergieStV",
  "EinsatzWVG",
  "BGSNeuRegG",
  "BAVSitzBek",
  "MntDAIVVDV",
  "EndlSiUntV",
  "PStSAG NRW",
  "SH AZVO SH",
  "DruckMstrV",
  "BbgSpkG BB",
  "MBergBGebV",
  "BGSVVermG",
  "BayDSG BY",
  "BTAuflAnO",
  "PBNUBestV",
  "4. FBG SN",
  "HaWiAusbV",
  "LuftVStDV",
  "BremBG HB",
  "TIntG NRW",
  "StiftG MV",
  "OrgBAusbV",
  "CW VO NRW",
  "RindSalmV",
  "BGRWidAnO",
  "LKatSG SH",
  "HmbVgG HH",
  "EstrMstrV",
  "BanQNormV",
  "FMSAKostV",
  "HmbKGH HH",
  "BbgBKG BB",
  "HZulG LSA",
  "SolingenV",
  "StrabBlPV",
  "KVHilfsmV",
  "BbgMFG BB",
  "BayEFG BY",
  "LBesG NRW",
  "BayFAG BY",
  "BayPrG BY",
  "VAGBbg BB",
  "VersVergV",
  "HArchDVDV",
  "ZStVBetrV",
  "HdGStiftG",
  "WaldG LSA",
  "LSchlG SL",
  "KondMstrV",
  "JKGBbg BB",
  "ErhMischV",
  "HBankDVDV",
  "GFlVermNV",
  "FIDEVerzV",
  "NJagdG NI",
  "LStatG MV",
  "IZG-SH SH",
  "LKatSG MV",
  "StVRAusnV",
  "BausparkV",
  "DRVBWG BW",
  "HmbJAG HH",
  "LaplaG SH",
  "ProMusErl",
  "BMFBDGAnO",
  "EGovG NRW",
  "StabMechG",
  "GenTAufzV",
  "IserlohnV",
  "HeimPersV",
  "BMLErnAnO",
  "StiftG SL",
  "UhrmAusbV",
  "BImADiszV",
  "EnSikuMaV",
  "HaSiG NRW",
  "FinDFwPrV",
  "KInvFErrG",
  "KiStG Bln",
  "KiBiz NRW",
  "NPBefVMVK",
  "FlugfunkV",
  "LVwVfG BW",
  "PersVEntV",
  "EWKKennzV",
  "HalblSchG",
  "AgrarOLkV",
  "YUGStrGHG",
  "BioStoffV",
  "RehaErstV",
  "RechZahlV",
  "AllGO LSA",
  "GravMstrV",
  "KunstUrhG",
  "VGebO Bln",
  "SchwSalmV",
  "ProstSchG",
  "EnSTransV",
  "GKrimDVDV",
  "BannMG HE",
  "EheschlRG",
  "KHZVV NRW",
  "MbauMstrV",
  "InsoKostV",
  "LHebG NRW",
  "RusslKVUV",
  "TexRAusbV",
  "MiLoAufzV",
  "BayKrG BY",
  "MietNEinV",
  "SeilAusbV",
  "VAbstG BW",
  "BestMstrV",
  "TabakerzG",
  "HoBaMstrV",
  "UhrmMstrV",
  "BauZAusbV",
  "FMSASatzV",
  "GrImpfSRV",
  "VAbstO SL",
  "HVwVfG HE",
  "LVwVfG RP",
  "VollstrPV",
  "ArchG LSA",
  "IntErbRVG",
  "OrdenGBek",
  "JMBStiftG",
  "BbgJAO BB",
  "GalvMstrV",
  "KernbrStG",
  "GastStaaG",
  "BayLBG BY",
  "BayESG BY",
  "KochAusbV",
  "AusbEignV",
  "BMASBGebV",
  "LwMstrPrV",
  "RStruktFV",
  "LwAltschV",
  "PersVG HB",
  "LMinG NRW",
  "MilchErzV",
  "RettungsG",
  "LJagdG HB",
  "LKatSG BW",
  "LwAltschG",
  "RebflRodV",
  "PostbAGSa",
  "HSchlG HE",
  "WerkeRegV",
  "HWaldG HE",
  "EStFreigG",
  "LWaldG HH",
  "DSO-LT SH",
  "SH.LVO SH",
  "FinHSaarG",
  "FinDAGebV",
  "BPolZollV",
  "ChemAusbV",
  "BAFABGebV",
  "CSCGKostO",
  "COV19KFVV",
  "GemHVO RP",
  "RDeckInfV",
  "BestG NRW",
  "KosmetikV",
  "BbgRiG BB",
  "BAPauschV",
  "BesamErlV",
  "DrittelbG",
  "AO-GS NRW",
  "AO-SF NRW",
  "LWappG TH",
  "AGFGO LSA",
  "SAGBMG SL",
  "SammlG RP",
  "ErgThAPrV",
  "BauKaG BY",
  "KraftwPrV",
  "GnadenAnO",
  "HebBO NRW",
  "VwVKVO MV",
  "NStatG NI",
  "AufbauhfV",
  "PostBATZV",
  "NVersG NI",
  "BezVWG HH",
  "FlexMstrV",
  "LWaldG BW",
  "WeinVergV",
  "BremHG HB",
  "PStVO NRW",
  "BfJEAktfV",
  "LWahlG SH",
  "ZuckQuotV",
  "RevjAusbV",
  "BDGBMIAnO",
  "UhVorschG",
  "LStatG HB",
  "VwVfG LSA",
  "GewRV NRW",
  "NWappG NI",
  "HmbKHG HH",
  "WStHAusbV",
  "AGVwGO RP",
  "VersVermV",
  "RechVersV",
  "BayRDG BY",
  "KapVO NRW",
  "AGInsO SH",
  "KonjStatV",
  "ArbZAusnV",
  "G 10DG SL",
  "HJagdG HE",
  "OlympSchG",
  "BestG Bln",
  "LuftGerPV",
  "NotVO NRW",
  "ImmoKWPLV",
  "SeehFinHG",
  "GefStoffV",
  "SchoMstrV",
  "GArchDVDV",
  "RohrFLtgV",
  "LJagdG BW",
  "GleiStatV",
  "TierSchlV",
  "ProdHaftG",
  "DachAusbV",
  "LKrWG NRW",
  "BMZWidAnO",
  "EltZSoldV",
  "FotoAusbV",
  "GLKrWG BY",
  "DaTraGebV",
  "BVerfSchG",
  "BbgFAG BB",
  "SachvRatG",
  "VerkStatG",
  "HwVerwdtV",
  "ModGAufhG",
  "BayStG BY",
  "PrfgZAUAV",
  "SchSiHafV",
  "EBArbSchV",
  "LArchG BW",
  "ZAGMonAwV",
  "RettDG RP",
  "LWaldG SH",
  "GBBStatut",
  "AMGBefugV",
  "LMinG LSA",
  "LBesG LSA",
  "EinhZeitG",
  "HalblSchV",
  "GewStUEzV",
  "NKatSG NI",
  "SVwVfG SL",
  "ZupfMstrV",
  "NKomVG NI",
  "BayBGG BY",
  "GebrMGBek",
  "BayVSG BY",
  "SeilMstrV",
  "VergMstrV",
  "SeeSchMpG",
  "BbgFGG BB",
  "JustG NRW",
  "BfNatSchG",
  "SaatBeihV",
  "GKGBbg BB",
  "LAufnG SH",
  "MiLoMeldV",
  "AG BtG BW",
  "InsOAG MV",
  "BannMG BW",
  "BbgGDG BB",
  "VAbstG HH",
  "BiomasseV",
  "BetrSichV",
  "StoffBilV",
  "EdWBeitrV",
  "AuslPflVG",
  "ArbPlSchG",
  "VAbstG SH",
  "SchafHKlV",
  "HmbBGG HH",
  "ImmoWertV",
  "KiStRG NI",
  "RStruktFG",
  "AusfErstV",
  "SparkG HB",
  "BebiG Bln",
  "MagGBV HB",
  "EWKFondsG",
  "LStatG BW",
  "GntDSVVDV",
  "3. FBG SN",
  "BremDG HB",
  "BaustellV",
  "TBetrWPrV",
  "KohleUGrV",
  "BAZustAnO",
  "BayRiG BY",
  "GewStMEAG",
  "HAbgG NRW",
  "LWahlG RP",
  "BremWG HB",
  "KatSG Bln",
  "TierNebBV",
  "LPZVO NRW",
  "PAuswGebV",
  "MarktAngV",
  "HmbGDG HH",
  "MessEGebV",
  "EinbTestV",
  "GGArt45cG",
  "VulkAusbV",
  "BzKJBGebV",
  "EinsatzUV",
  "EnSimiMaV",
  "UntAG Bln",
  "SanDVergV",
  "EStSchlEV",
  "TelekAGSa",
  "HKEntschG",
  "BSGWidAnO",
  "JKostG HB",
  "HwREintrV",
  "EBPensNOG",
  "KapErhStG",
  "SchulG RP",
  "BbgNRG BB",
  "DONot LSA",
  "CoronaNLB",
  "LjagdG MV",
  "AsylVfGNG",
  "KosmAusbV",
  "VAFreistV",
  "SV-VO NRW",
  "GemKVO HE",
  "JagdzeitV",
  "TranspRLG",
  "GeschGehG",
  "PackungsV",
  "HmbRiG HH",
  "VerdStatG",
  "MuKStiftG",
  "BMJErnAnO",
  "HBauStatG",
  "NDiszG NI",
  "ViehVerkV",
  "GflSalmoV",
  "IsolMstrV",
  "MaskAusbV",
  "BASPOErmV",
  "MBankDVDV",
  "AKEVO NRW",
  "VersG NRW",
  "DSchG Bln",
  "AufwErstV",
  "BayPVG BY",
  "AGVwGO HB",
  "AGInsO RP",
  "HmbDSG HH",
  "KondAusbV",
  "AGVwGO BY",
  "PTZustAnO",
  "TelemGebV",
  "FischG BW",
  "ZertVerwV",
  "LJagdG SH",
  "AGVwGO BW",
  "BayGlG BY",
  "KaffeeStG",
  "GemHVO BW",
  "BPAAusglV",
  "SchBG Bln",
  "LWaldG MV",
  "WBeauftrG",
  "KonzVO MV",
  "MarktOWMG",
  "BeglV NRW",
  "BbgSGG BB",
  "SaatAufzV",
  "GenTPflEV",
  "FleiMstrV",
  "SchfAusbV",
  "LAbfWG SH",
  "TabakerzV",
  "SGerOG SL",
  "BMELBGebV",
  "JStVollzG",
  "KryptoFAV",
  "StabiRatG",
  "BMIErnAnO",
  "DBUStiftG",
  "CSCGZulSV",
  "GemKVO RP",
  "StrUG NRW",
  "KPBVO NRW",
  "SHBesG SH",
  "KonsHilfG",
  "RTrAbwGDV",
  "KhWbAusbV",
  "BinSchSiV",
  "SchAG NRW",
  "NichtAnpG",
  "WSPVO NRW",
  "KraftStDV",
  "PersVG MV",
  "SeeFSichV",
  "BayRKG BY",
  "FeuVO NRW",
  "HeNatG HE",
  "LStatG SH",
  "GeflPestV",
  "BewG122DV",
  "FerReiseV",
  "HFKVO NRW",
  "KaFbMstrV",
  "EigVO NRW",
  "AgrarOLkG",
  "EigBG LSA",
  "KiStG NRW",
  "ZollKostV",
  "InVeKoSDG",
  "KaffeeStV",
  "DiszG Bln",
  "StrWG NRW",
  "BayFiG BY",
  "EMVBeitrV",
  "LSubvG BW",
  "DestAusbV",
  "ContStifG",
  "LWaldG SL",
  "LArchG RP",
  "DSchG LSA",
  "IntFamRVG",
  "RechPensV",
  "LBesG Bln",
  "VwVfG NRW",
  "NKFEG NRW",
  "PatKostZV",
  "LorbBlErl",
  "VerfGG HH",
  "InsOAG BW",
  "AsphAusbV",
  "GBankDVDV",
  "GebrMstrV",
  "LAbgG Bln",
  "SchwPestV",
  "2. FBG SN",
  "BbgJAG BB",
  "HSchAG HE",
  "LSubvG RP",
  "FraktG HE",
  "LBodSchAG",
  "BremLV HB",
  "HmbLVO HH",
  "BWildSchV",
  "NArchG NI",
  "MarktOWMV",
  "EnWGKostV",
  "HanfEinfV",
  "EVZStiftG",
  "NachbG HE",
  "SchnellLG",
  "KrAbwFBek",
  "AuslZustV",
  "GenTNotfV",
  "BildUG HH",
  "LuftPersV",
  "TT-VgG HB",
  "VersammlG",
  "UKBVO Bln",
  "RechKredV",
  "LwRentBkG",
  "StiftG BW",
  "GOLReg BB",
  "GefOrdErl",
  "FraktG BB",
  "TechFwPrV",
  "HessHG HE",
  "LStatG RP",
  "LuftNaSiG",
  "SchulG SH",
  "LWaldG RP",
  "BayKSG BY",
  "FleiAusbV",
  "AMRabattG",
  "RUAStrGHG",
  "NVwVfG NI",
  "StIKoVetV",
  "AbfVerbrG",
  "KiStG LSA",
  "LuftKostV",
  "EinhRSprG",
  "StBegrAnO",
  "ZinsSatzV",
  "StrWAusbV",
  "GarVO NRW",
  "AGGVG LSA",
  "WiFaWiPrV",
  "BPAWidAnO",
  "BwTAMAbgV",
  "KartKostV",
  "ITSEAusbV",
  "SchulG MV",
  "SVZustAnO",
  "LSchV NRW",
  "NStGHG NI",
  "BeschussV",
  "AGInsO HE",
  "BayHIG BY",
  "GefBeitrV",
  "ArbZVO RP",
  "HAKrWG HE",
  "FlugDaGEG",
  "HDSchG HE",
  "GLKrWO BY",
  "ElekAusbV",
  "GtDWSVVDV",
  "KapAusstV",
  "FinVmVtrG",
  "BVOTb NRW",
  "JArbSchUV",
  "DerivateV",
  "BWpVerwPG",
  "RettG NRW",
  "SeeFischG",
  "VerbrBekG",
  "DBAGZustV",
  "BauSparkG",
  "LWaldG BB",
  "StiftFinG",
  "WohnImRiV",
  "FraktG BW",
  "RundfG MV",
  "IHRABefV",
  "NStrG NI",
  "AMPreisV",
  "AGSGG BW",
  "HIngG HE",
  "BwVollzO",
  "OSZEVorV",
  "LPlG NRW",
  "NetzResV",
  "StGHG HE",
  "SeeAufgG",
  "LGebG BW",
  "StromPBG",
  "AusglZAV",
  "DEFondsB",
  "NAbgG NI",
  "WPostVVG",
  "PauschAV",
  "AltfAbwG",
  "KiStG SH",
  "BilKoUmV",
  "THAKredG",
  "NHZVO NI",
  "GeoEngBV",
  "HBesG HE",
  "BedGgstV",
  "AWKG NRW",
  "EBABGebV",
  "NRSG LSA",
  "EGDMailG",
  "AMAnwLwV",
  "AMSachvV",
  "UVPG LSA",
  "GeoNutzV",
  "UVPG-Bln",
  "NVwZG NI",
  "BNatSchG",
  "VOFF NRW",
  "FinVermV",
  "EltLastV",
  "BLBG NRW",
  "BSIZertV",
  "ErstAnzV",
  "LOWiG BW",
  "AZVO NRW",
  "SUVPG SL",
  "KonstPrV",
  "LuftVGBV",
  "SchoG SL",
  "StromStV",
  "LVwVG BW",
  "BerRehaG",
  "BergWoZV",
  "BestG HB",
  "PflegeVG",
  "LFKV NRW",
  "GnadG SL",
  "LStVG BY",
  "AGBGB BW",
  "PSVO NRW",
  "WoVermRG",
  "StimmRMV",
  "GKVBegrG",
  "SPolG SL",
  "AMSachKV",
  "VSBInfoV",
  "AzUVO BW",
  "BestG NI",
  "KredSanG",
  "AromenDV",
  "RefiRegV",
  "ZirkRegV",
  "LEntG MV",
  "WDRG NRW",
  "UVPPortV",
  "AntHaftG",
  "APAEinrG",
  "MVTAusbV",
  "KerAusbV",
  "VersMedV",
  "BegleitG",
  "SchAusrV",
  "BerVersV",
  "SysStabV",
  "VerpackV",
  "AusglZSV",
  "HkGAufhG",
  "DBASGPNV",
  "KiStG BW",
  "BeamtStG",
  "BayBG BY",
  "BMIBGebV",
  "StrRehaG",
  "AMStRegV",
  "AntiDopG",
  "RaumAPrV",
  "ZimMstrV",
  "AufenthG",
  "LVwVG RP",
  "AGBGB RP",
  "IngG LSA",
  "LEntG BW",
  "FlUStatV",
  "HBauO HH",
  "FrFG LSA",
  "SpkG NRW",
  "NRSG Bln",
  "LadSchlG",
  "AufenthV",
  "ArchG BW",
  "VereinsG",
  "PTStiftG",
  "StromNZV",
  "AltholzV",
  "DMBeEndG",
  "BMUBGebV",
  "PFoG NRW",
  "StWG NRW",
  "LBAV NRW",
  "NJAVO NI",
  "PSchG BW",
  "JAVollzO",
  "PBLEntgV",
  "LMinG MV",
  "StVollzG",
  "BelWertV",
  "PolG NRW",
  "GeschmMG",
  "ErbbauRG",
  "InVeKoSV",
  "SeeLAuFV",
  "GO LT BB",
  "HRegGebV",
  "SaatgutV",
  "AdVermiG",
  "AGFGO SL",
  "InfrGGBV",
  "LPachtVG",
  "KiBoNiAG",
  "BMeldDAV",
  "BauO Bln",
  "PatAnwVV",
  "BKOrgErl",
  "WBStiftG",
  "KSVEntgV",
  "UStZustV",
  "EStZustV",
  "FluVGBek",
  "LVLG NRW",
  "ArbMedVV",
  "KiStG MV",
  "EntwLStG",
  "FSPersAV",
  "KfSachvG",
  "MPDGGebV",
  "LSVFGErG",
  "AGSGG RP",
  "HaftPflG",
  "TerrOIBG",
  "LMTAusbV",
  "HebStPrV",
  "LuftFzgG",
  "BAAZustV",
  "ArchG RP",
  "HAZVO HE",
  "BKleingG",
  "HAfAuflG",
  "Verf LSA",
  "IUCNVorV",
  "DSLBUmwG",
  "LPVG NRW",
  "HZAZustV",
  "VidVerfG",
  "ITZBundG",
  "AbgG NRW",
  "AMStZulV",
  "DPWidAnO",
  "AMEG NRW",
  "NiRSG RP",
  "SchRegDV",
  "DSchG MV",
  "StGHG HB",
  "StrlSchV",
  "StromStG",
  "EigVO MV",
  "FWiStatV",
  "AuslInvG",
  "VermAnlG",
  "AufnG NI",
  "ZDPersAV",
  "BkAZustV",
  "PharmStV",
  "SchlG BW",
  "VwVfG MV",
  "APOGV SN",
  "GemKV BB",
  "DBPBRAnO",
  "MilchPrV",
  "AtSKostV",
  "AC-G NRW",
  "BeVO NRW",
  "AltZertG",
  "BBodSchV",
  "SchwHKlV",
  "BbgPG BB",
  "GebG NRW",
  "StrWG SH",
  "GO LT MV",
  "NAbfG NI",
  "BMGBGebV",
  "HmbHG HH",
  "LKrWG RP",
  "GKVStabG",
  "BezWG BY",
  "SGBBeglV",
  "VersRuhG",
  "VerbrKrG",
  "VerkDSpG",
  "BGBAG HH",
  "BayDG BY",
  "EigVO SL",
  "KlagRegV",
  "DSAG LSA",
  "VermBezV",
  "EBIZustV",
  "NUVPG NI",
  "DSchG HH",
  "PflegeZG",
  "COV19FKG",
  "BHKG NRW",
  "L-BGG BW",
  "BewG90DV",
  "VwZVG BY",
  "GPAG NRW",
  "PostUmwG",
  "PTBBGebV",
  "AEAusglV",
  "EZVO NRW",
  "BayBO BY",
  "SchwbAwV",
  "LGebG RP",
  "NotViKoV",
  "AGSGG BY",
  "MitbestG",
  "OffshStG",
  "ArchG MV",
  "RundfNOG",
  "FrStllgV",
  "NVwVG NI",
  "BayWG BY",
  "LPresseG",
  "SSchO SL",
  "FinDASaV",
  "AuswGebV",
  "PWMAusbV",
  "VSGZustV",
  "EEZV NRW",
  "HRWG NRW",
  "FPMMstrV",
  "MautVvfV",
  "DGBankSa",
  "BeiratsV",
  "PostAGSa",
  "BienSchV",
  "IngG NRW",
  "SanInsKG",
  "LBesG RP",
  "BayJG BY",
  "AWbG NRW",
  "BinSchZV",
  "KHGG NRW",
  "SchutzmV",
  "TierNebG",
  "WaffRGDV",
  "FleischG",
  "EComFPrV",
  "SchBFFlV",
  "LfbG Bln",
  "AbfG LSA",
  "HypErklG",
  "PatKostG",
  "InsStatG",
  "WechselG",
  "OPrAGebG",
  "ArbGG BW",
  "ImmVermV",
  "HStruktG",
  "GSIAusbV",
  "LRH-G SH",
  "PsychThV",
  "AGSGG HE",
  "FZVAusnV",
  "VEPPGewG",
  "ZustAnpG",
  "HWVO NRW",
  "ZVGV NRW",
  "TSEResZV",
  "BAMG Bln",
  "KfSachvV",
  "MuLMstrV",
  "AgrStatG",
  "EntschRG",
  "APASGebV",
  "ZPOAG HB",
  "FGOAG HH",
  "GesBergV",
  "FeinGehG",
  "UmweltHG",
  "GasLastV",
  "PflSchMV",
  "KomWG BW",
  "HmbBG HH",
  "VIBBestV",
  "BrbMstrV",
  "WindSeeG",
  "AMBtAngV",
  "ScharkaV",
  "BayMG BY",
  "NIngG NI",
  "AuswErlV",
  "SymbolVO",
  "MForschG",
  "StrlSchG",
  "HDSIG HE",
  "SGGAG HH",
  "BayHO BY",
  "OrdenErl",
  "NBesG NI",
  "AufhFErG",
  "BierStDB",
  "TierNebV",
  "ErhSortV",
  "THWMitwV",
  "NSchG NI",
  "PsychThG",
  "VerpackG",
  "LMBestrV",
  "WissBdVV",
  "EUBeitrG",
  "BeauftrV",
  "ArbnErfG",
  "MahnVfVV",
  "JuZuV HE",
  "KugverlV",
  "LRiG LSA",
  "BVSAuflG",
  "SiMedErl",
  "BayDO BY",
  "LBtG NRW",
  "MilzbRbV",
  "PflKartV",
  "BtMBinHV",
  "AZVO Bln",
  "DSchG RP",
  "PreisKlG",
  "GAPKondG",
  "LWKG NRW",
  "STFLG SL",
  "VREVerVV",
  "SchuTSEV",
  "AGBMG RP",
  "LRHG LSA",
  "LRKG NRW",
  "CorWaldG",
  "SokaSiG2",
  "FSBeitrV",
  "GemHV BB",
  "GO LT HE",
  "FachbPrV",
  "FinStabG",
  "AbfWG MV",
  "SGleibWV",
  "MariMedV",
  "BewG81DV",
  "OrthoptG",
  "LUKG NRW",
  "LUVPG MV",
  "LFoG NRW",
  "SpkG Bln",
  "IHKG NRW",
  "VwVG NRW",
  "WFNG NRW",
  "HmbDG HH",
  "BVARKAnO",
  "LVerf HB",
  "SchildlV",
  "StromGVV",
  "SchwbVWO",
  "KiStG RP",
  "PsychPbG",
  "LeukoseV",
  "RentEPPG",
  "GemAusGO",
  "BayRG BY",
  "HStrG HE",
  "HNtV NRW",
  "BGGWEntG",
  "LGBG Bln",
  "BestattG",
  "TierGesG",
  "AuslAdMV",
  "MautSysG",
  "ArztBAVG",
  "BinSchUO",
  "LPrG NRW",
  "BogMstrV",
  "StrG LSA",
  "KfzPflVV",
  "MautRegV",
  "StFoG BY",
  "IntTestV",
  "BestG RP",
  "BPersVWO",
  "HSchG HE",
  "LKRG NRW",
  "WpDVerOV",
  "BbgWG BB",
  "ZVSAusbV",
  "SVwVG SL",
  "KomWO BW",
  "AufnG BY",
  "VReformG",
  "GHBG NRW",
  "HKohlStG",
  "StromNEV",
  "WOSprAuG",
  "UVPG NRW",
  "LKJHG BW",
  "AltvPIBV",
  "BauO LSA",
  "AMVerkRV",
  "GOReg SL",
  "KraftNAV",
  "BewachRV",
  "ElektroG",
  "DeckRegV",
  "JArbSchG",
  "GOBVerfG",
  "EigG Bln",
  "RindHKlV",
  "AHStatDV",
  "EmsSchEV",
  "AbgG LSA",
  "LBauO RP",
  "BGVPLTDV",
  "HopfEinV",
  "BMGAG HE",
  "EiVermNV",
  "TrainerV",
  "GenTAnhV",
  "IngG Bln",
  "MiLoDokV",
  "TauchPrV",
  "BKMBGebV",
  "BestG BY",
  "DIVIRegV",
  "KomWG SN",
  "DSchG NI",
  "PflAFinV",
  "MRVG NRW",
  "RSMAusbV",
  "NBauO NI",
  "KiStG HB",
  "GlVO NRW",
  "SozhiDAV",
  "BBodSchG",
  "LMinG NI",
  "BAMBGebV",
  "GenTBetV",
  "AgrStatV",
  "WaStrAbG",
  "FernAbsG",
  "BDGPNEDV",
  "NotAktVV",
  "SVerf SL",
  "ModMstrV",
  "LStrG RP",
  "FVerkWBV",
  "WasMotRV",
  "HkRNGebV",
  "ProMechG",
  "FlaggAnO",
  "VAwS NRW",
  "RAVG Bln",
  "VkVO NRW",
  "LuftRegV",
  "OrgG LSA",
  "BevStatG",
  "BMMAusbV",
  "BinSchLV",
  "BArtSchV",
  "GBFVO NI",
  "AllGO NI",
  "NelkenwV",
  "SDLWindV",
  "EisAusbV",
  "LRHG NRW",
  "ERVDPMAV",
  "GOrgG BW",
  "LuftSiAV",
  "GO LT SL",
  "Verf NRW",
  "GAPStatG",
  "ProMusRL",
  "EUObstGV",
  "AbgEG RP",
  "BinSchEO",
  "EUKiGAbV",
  "SHRDG SH",
  "LuftVStG",
  "UStErstV",
  "ASOG Bln",
  "KHZV NRW",
  "BLEZustV",
  "LpflG BW",
  "VwVG LSA",
  "TierSchG",
  "EuropolG",
  "ZuckArtV",
  "ZahlVGJG",
  "StatRegG",
  "LUVPG SH",
  "VfGHG BY",
  "UmwAusbV",
  "ASGZustV",
  "LBauO MV",
  "FrHfErrG",
  "HmbSG HH",
  "EGBVO MV",
  "VerjHemV",
  "BinSchGG",
  "RVRG NRW",
  "BaubetrV",
  "VersatzV",
  "VbrInsFV",
  "DSchG BW",
  "GkG NRW",
  "SatDSiV",
  "LDSG SH",
  "ZahnFAG",
  "NLVO NI",
  "AdWirkG",
  "LFAG RP",
  "LPrG MV",
  "KrArchG",
  "SFTG SH",
  "LGG Bln",
  "HHZV HE",
  "ESMFinG",
  "SchfHwG",
  "VermBDV",
  "ZweckVG",
  "LplG BW",
  "WPersAV",
  "BGJAnrV",
  "PfandlV",
  "JAPO BY",
  "AROG SL",
  "LWaG MV",
  "SHStatG",
  "SprengG",
  "AABGebV",
  "JVKostG",
  "WasSkiV",
  "MedBVSV",
  "LBWG BW",
  "VAErstV",
  "SaAusbV",
  "FernUSG",
  "HwStatG",
  "LZG NRW",
  "SBKG SL",
  "PodAPrV",
  "BOKraft",
  "FStrAbG",
  "PKGG BY",
  "LegRegV",
  "GMAusbV",
  "VwRehaG",
  "FIAusbV",
  "SpkG RP",
  "NROG NI",
  "JAG LSA",
  "SHSG SL",
  "SchG BW",
  "LHO NRW",
  "BImSchG",
  "IFGGebV",
  "Art115V",
  "GDG Bln",
  "BVO NRW",
  "SpkG BY",
  "LUKG MV",
  "UAGGebV",
  "GWDAPrV",
  "GewSchG",
  "BSchuWV",
  "GewAbfV",
  "KWKAusV",
  "RindTbV",
  "NKAG NI",
  "ErnG BW",
  "EGBusDV",
  "ParlStG",
  "IngG MV",
  "KOG NRW",
  "KHV NRW",
  "BAPostG",
  "KVG LSA",
  "HFG NRW",
  "AusgStG",
  "JAVO SH",
  "KaffeeV",
  "GvKostG",
  "MRVG SL",
  "SanktDG",
  "PostSZV",
  "ScheckG",
  "GOLT RP",
  "JAG NRW",
  "BWG Bln",
  "GenRegV",
  "SchO SH",
  "OBG NRW",
  "AntKomV",
  "SpruchG",
  "DruckLV",
  "LDSG RP",
  "BArchBV",
  "HMG NRW",
  "IGG NRW",
  "PolG BW",
  "AMFarbV",
  "LRHG NI",
  "EnSiTrV",
  "LVO LSA",
  "TierZEV",
  "NDSG NI",
  "LBVG BW",
  "FBeitrV",
  "NESG NI",
  "NatSchG",
  "BGremBG",
  "GDG LSA",
  "RSiedlG",
  "NJAG NI",
  "StVertV",
  "APG NRW",
  "KredAAG",
  "KrO NRW",
  "LHO Bln",
  "Verf HH",
  "StAuskV",
  "NLWO NI",
  "LegRegG",
  "AHStatG",
  "LuftVZO",
  "KHStatV",
  "LlbG BY",
  "VermAGO",
  "LRiG SH",
  "FStrBAG",
  "SKHG SL",
  "NSGKdrV",
  "GhRentG",
  "GVIDVDV",
  "KHEntgG",
  "LogAPrO",
  "FKAustG",
  "NotV BY",
  "NSGFmbV",
  "FSStrKV",
  "VfAusbV",
  "MinG SL",
  "BFStrMG",
  "SLVO SL",
  "EglG BW",
  "BWFSPrV",
  "PflSchG",
  "NSGBRgV",
  "LRHG MV",
  "VStFStG",
  "LNRG RP",
  "GewAnzV",
  "BIBBBek",
  "SatDSiG",
  "NotSanG",
  "LBG Bln",
  "SLPG SL",
  "HKHG HE",
  "UAG LSA",
  "BhVO SL",
  "OldenbG",
  "KiGAnrG",
  "ASchulG",
  "LNRSchG",
  "JAPG HB",
  "LKG Bln",
  "SAWG SL",
  "KomtrZV",
  "ForumRG",
  "DeMailG",
  "VAAufsG",
  "BewachV",
  "HKWAbfV",
  "WDOBezV",
  "SeeAnlG",
  "SNHG HH",
  "FlugDaG",
  "VerschG",
  "SchBerG",
  "NSGSylV",
  "LRKG BW",
  "LKWG MV",
  "LRiG RP",
  "LHO LSA",
  "JAG Bln",
  "GKWG SH",
  "LJKG BW",
  "VSG Bln",
  "HRiG HE",
  "BSSichG",
  "BierStG",
  "GOLT SH",
  "KWO LSA",
  "DVLStHV",
  "SokaSiG",
  "RAVG RP",
  "AuslVZV",
  "SUKG SL",
  "FlBeihV",
  "EGGmbHG",
  "SchRegO",
  "BefBedV",
  "KrhWwSV",
  "EStiftG",
  "KWGAnwV",
  "BGG NRW",
  "LWO LSA",
  "UrhGBek",
  "HSG LSA",
  "InsVfVO",
  "AnlEntG",
  "SeeArbG",
  "DBBATZV",
  "SMVergV",
  "CorSurV",
  "KindUFV",
  "JAPO RP",
  "GrenzAV",
  "HeizkZG",
  "MPVerfV",
  "TrZollG",
  "InnAusV",
  "LZV NRW",
  "AISSeeV",
  "LKWO MV",
  "ProstAV",
  "GemO BW",
  "GenTVfV",
  "KFAG SL",
  "Verf HE",
  "SchBauG",
  "SUVO SH",
  "GrSiDAV",
  "LUKG BW",
  "WoStatG",
  "KSVG SL",
  "VSG NRW",
  "VVVG SN",
  "VSKG HE",
  "ThJG TH",
  "USchadG",
  "WbG NRW",
  "NKWG NI",
  "ATDZugV",
  "ALVO SH",
  "AZVO SL",
  "Verf TH",
  "AntiDHG",
  "RebPflV",
  "EigZulG",
  "ZensTeG",
  "LJKG HH",
  "NRiG NI",
  "NRSG SL",
  "BVersTG",
  "IngG BW",
  "TrZollV",
  "GlAusbV",
  "AbgG MV",
  "LRKG MV",
  "GGKostV",
  "AtDeckV",
  "VvB Bln",
  "PflAPrV",
  "LVV NRW",
  "HSOG HE",
  "FlAG MV",
  "IFG Bln",
  "WoBindG",
  "VglWebV",
  "ZAGAnzV",
  "LPVG BW",
  "BfAMBek",
  "SVersLV",
  "VerpflG",
  "TrinkwV",
  "PfandBG",
  "SSpG SL",
  "LPlG RP",
  "LPlG MV",
  "ErbStDV",
  "KAVO RP",
  "StrG SL",
  "ApBetrO",
  "AFVFinV",
  "SeilbDG",
  "AMGZSAV",
  "STGV SL",
  "GOLT BW",
  "BioAbfV",
  "AGSG BY",
  "HEEG HE",
  "ButterV",
  "FDNormV",
  "GrAusbV",
  "LBG LSA",
  "LVwG SH",
  "GebG HH",
  "HypAblV",
  "LRZG HB",
  "ArbSchG",
  "BWKAusl",
  "FrHAblG",
  "BSHGebV",
  "ErgAnzV",
  "PlanSiG",
  "LuftEBV",
  "NotrufV",
  "InsBekV",
  "NFAG NI",
  "LFGG BW",
  "HZG NRW",
  "HzG LSA",
  "MargMFV",
  "NNVG NI",
  "LRHG BB",
  "MarkenG",
  "DSG NRW",
  "KAVerOV",
  "NRSG SH",
  "LAV-NRW",
  "HWaG HH",
  "NPOG NI",
  "SOG LSA",
  "THWAbrV",
  "RTrAbwG",
  "HGlG HE",
  "BHfAbgV",
  "GleibWV",
  "BBankLV",
  "BITVNRW",
  "BWahlGV",
  "EGMRKHG",
  "NKWO NI",
  "SDSG SL",
  "GemO RP",
  "FPStatG",
  "EGSichV",
  "LVSG BW",
  "UVwG BW",
  "AZG Bln",
  "BetrAVG",
  "BierStV",
  "LbVO RP",
  "HRHG HE",
  "RAVG HB",
  "NLWG NI",
  "WFAusbV",
  "ALVO MV",
  "LGG NRW",
  "HASG HE",
  "SeefBgV",
  "VIGGebV",
  "LuftSiG",
  "EGWStrG",
  "HFAG HE",
  "BhVO SH",
  "BPolHfV",
  "JBeitrG",
  "OVP NRW",
  "BVerfGG",
  "StVZONB",
  "LKrO BW",
  "LArbWoV",
  "VerkPBG",
  "Verf BB",
  "LobbyRG",
  "SchwbAV",
  "LJKG SL",
  "KHStabG",
  "HVSG HE",
  "BwKoopG",
  "AMAusbV",
  "NtV NRW",
  "LIG LSA",
  "EntschG",
  "SRKG SL",
  "GroMiKV",
  "GstG SH",
  "HeilprG",
  "HBKG SH",
  "WeinSBV",
  "LDG NRW",
  "HBKG HE",
  "AZVO MV",
  "ABBergV",
  "HLbG HE",
  "Verf SH",
  "LJG-NRW",
  "Verf BY",
  "AktuarV",
  "StStatG",
  "SpkG SH",
  "KonzVgV",
  "AISEmsV",
  "KUV NRW",
  "KrhSurV",
  "GFABPrV",
  "SpkG MV",
  "POG NRW",
  "OpfBGEG",
  "LWG NRW",
  "KAG NRW",
  "UAGAnwG",
  "AbgGBek",
  "HeilVfV",
  "IHKG BW",
  "HdBALBV",
  "MFKRegV",
  "StrFinG",
  "StrG BW",
  "REDZugV",
  "RAVG SH",
  "StiftRG",
  "VerkSiG",
  "LKHG BW",
  "SHzG SL",
  "GPAG BW",
  "WuSolvV",
  "RHG Bln",
  "JAPO MV",
  "AMWarnV",
  "KrAbwFG",
  "JWMG BW",
  "DatErhV",
  "NSGDgbV",
  "BOStrab",
  "HeimmwV",
  "BinSchG",
  "BGleiSV",
  "GewStDV",
  "BluPanV",
  "LTAusbV",
  "ErbStRG",
  "WasserG",
  "Verf NI",
  "Verf MV",
  "UIGGebV",
  "MarkenV",
  "DesignV",
  "SchBesV",
  "EEG NRW",
  "LOG NRW",
  "EigV BB",
  "FinDASa",
  "NSVerbG",
  "FStrKrV",
  "HwWahlO",
  "KWG LSA",
  "NbG LSA",
  "LFtG RP",
  "IFG NRW",
  "UIG NRW",
  "Verf RP",
  "GaFinHG",
  "HWBG HE",
  "HPMG HE",
  "VBD NRW",
  "IngG SL",
  "HinSchG",
  "WahlPrG",
  "SpkG HE",
  "StraBEG",
  "LDSG BW",
  "StandAG",
  "SchauHV",
  "NSpG NI",
  "PatGBek",
  "LMG NRW",
  "LBKG RP",
  "BFDZenV",
  "NHZG NI",
  "HAKA HE",
  "HzG Bln",
  "LwAusbV",
  "NKPG NI",
  "MinG BW",
  "LWPG RP",
  "SchAnpG",
  "AsylZBV",
  "BMVergV",
  "BPersVG",
  "BGAktFV",
  "BuchPrG",
  "PflGesG",
  "GStDVDV",
  "RAVG BW",
  "MFG LSA",
  "NSGPBRV",
  "LRHG TH",
  "RiRegDG",
  "UrhUSAG",
  "LKrO BY",
  "PortalV",
  "MBVerfV",
  "GVVG BY",
  "BeamtVG",
  "SAIG SL",
  "KaseinV",
  "EnStatG",
  "JAO Bln",
  "GOLR MV",
  "KapResV",
  "MStDVDV",
  "RDG Bln",
  "WoVermG",
  "PostAZV",
  "LVO NRW",
  "KHG NRW",
  "KHG LSA",
  "HZVO BW",
  "Verf SN",
  "LEG LSA",
  "LAArchV",
  "GrdstVG",
  "MinG SH",
  "DesignG",
  "FAG LSA",
  "AnwZpvV",
  "TierZDV",
  "HolzSiG",
  "BSchuWG",
  "GewebeG",
  "HPVG HE",
  "AsylbLG",
  "RAVG SL",
  "PolBTLV",
  "BefBezG",
  "NSGBefV",
  "LWG LSA",
  "AltvDV",
  "PlanZV",
  "WG LSA",
  "BlutZV",
  "LJG RP",
  "AktFoV",
  "LHO MV",
  "SWG SL",
  "MNrVAL",
  "SprAuG",
  "VFBAZV",
  "SGG HB",
  "InVorG",
  "DG LSA",
  "ASORDV",
  "StiftG",
  "BSAVfV",
  "RentSV",
  "HDG HE",
  "LHG MV",
  "MFG SL",
  "HWG HE",
  "LVG BW",
  "FBG SN",
  "AGVwGO",
  "MessEG",
  "VerstV",
  "GAPDZV",
  "VKO HH",
  "HonigV",
  "LDG SH",
  "HG NRW",
  "GebrMG",
  "BBergG",
  "UStatG",
  "BGeoRG",
  "WindBG",
  "NBG NI",
  "AnerkV",
  "GasNZV",
  "TollwV",
  "BeschV",
  "KUV BY",
  "LGG SL",
  "RegMoG",
  "LVO BW",
  "LBG BW",
  "WPAnrV",
  "SDG SL",
  "RiG MV",
  "HGO HE",
  "KrO SH",
  "HKO HE",
  "UAG BB",
  "BtMAHV",
  "LGG BB",
  "IStGHG",
  "BMJMBG",
  "UZwGBw",
  "BBankG",
  "AWaffV",
  "LHO BB",
  "FAG SH",
  "NLPosV",
  "PAG TH",
  "LEG HH",
  "HdlKlG",
  "KAG BW",
  "GAufzV",
  "MTAPrV",
  "ENeuOG",
  "BKrFQG",
  "LHO NI",
  "GKZ BW",
  "NJG NI",
  "LDG RP",
  "LHO RP",
  "UAG BW",
  "VSBGEG",
  "SBG HB",
  "StipHV",
  "BfAIPG",
  "MauerV",
  "GNotKG",
  "KrimLV",
  "BeschG",
  "BKrFQV",
  "LOG BB",
  "EUAHiG",
  "GeolDG",
  "WSAnpB",
  "BWahlG",
  "POG MV",
  "ErgThG",
  "LBG SH",
  "WissFG",
  "PEntgV",
  "KGG HE",
  "UrhDaG",
  "BPolZV",
  "TPG TH",
  "GGBefG",
  "FPersG",
  "HDO HE",
  "VVG BB",
  "MindZV",
  "KOVVfG",
  "FAG MV",
  "BmAusV",
  "AlkStV",
  "StAbwV",
  "HkRNDV",
  "PartGG",
  "BKompV",
  "KugBeV",
  "LHeimG",
  "LEG HB",
  "ZollVG",
  "GBBerG",
  "WaffRG",
  "SDO SL",
  "LPartG",
  "InfrGG",
  "UAGZVV",
  "SVertO",
  "WeinRV",
  "SBG SL",
  "POG SH",
  "MFG NI",
  "JAG BW",
  "SoldGG",
  "NeuGlV",
  "MG NRW",
  "HopfDV",
  "BesRNG",
  "LOG MV",
  "LWO SL",
  "JAG MV",
  "InvStG",
  "PAuswV",
  "LuftBO",
  "KakaoV",
  "LWG SL",
  "FMStBG",
  "LKG RP",
  "DaTraV",
  "EGStGB",
  "SJG SL",
  "FwG HH",
  "GebOSt",
  "HAuslG",
  "SeeAZV",
  "ErstrG",
  "BerHFV",
  "LBO BW",
  "EssigV",
  "DeckRV",
  "SaatIV",
  "FTG HB",
  "MiLoV4",
  "HSG SH",
  "GBZugV",
  "LWG SH",
  "ProdSG",
  "OBG BB",
  "SMG SL",
  "MaSanV",
  "ProstG",
  "HzG HE",
  "NVG RP",
  "ZApprO",
  "MLAnpV",
  "EGAktG",
  "EGInsO",
  "InfrAG",
  "AUGBek",
  "SaRegG",
  "SektVO",
  "EuAbgG",
  "HSeeZG",
  "PflvDV",
  "KAG BY",
  "BVwVfG",
  "GDolmG",
  "LTG SL",
  "RHG BY",
  "GewStG",
  "FahrlG",
  "AdLDAV",
  "UVOGrV",
  "LKO RP",
  "NHG NI",
  "GasNEV",
  "KInvFG",
  "PersBG",
  "LGG RP",
  "SFG SL",
  "RuStFG",
  "HStatG",
  "KrZwMG",
  "LBO SH",
  "NachwV",
  "GnO HE",
  "JAG SH",
  "JAG RP",
  "LBO SL",
  "NachwG",
  "ZustVV",
  "UnBefG",
  "RKErzG",
  "ForUmV",
  "BVersG",
  "GGVSee",
  "LVwVfG",
  "BEGTPG",
  "VkBkmG",
  "HBG HE",
  "BKMBek",
  "FMStFV",
  "GrEStG",
  "LWO BW",
  "VerkLG",
  "RHG SN",
  "LMG MV",
  "VermVV",
  "NEG NI",
  "SchStV",
  "GAPDZG",
  "KAG SH",
  "DepotG",
  "KiQuTG",
  "AlkStG",
  "LHG BW",
  "LWO SN",
  "UAG TH",
  "FPersV",
  "LMRStV",
  "SpaEfV",
  "KAG MV",
  "KWO RP",
  "StPOEG",
  "EUStBV",
  "DSG MV",
  "SpG BW",
  "ZVV BB",
  "IRegBV",
  "AufbhV",
  "BfkEEG",
  "SozSHV",
  "BVO BW",
  "BPolLV",
  "LMG SH",
  "MinStG",
  "POG RP",
  "BauNVO",
  "LHO HE",
  "KAG BB",
  "TrGebV",
  "StVorV",
  "GDG SH",
  "FZulBV",
  "SaGErl",
  "KWG SL",
  "SNG SL",
  "EAPatV",
  "GlStEG",
  "MBergG",
  "LDG MV",
  "RBG HB",
  "SchuFV",
  "BGleiG",
  "GenTSV",
  "EUStAG",
  "TierZG",
  "FTG BY",
  "StAbwG",
  "SpielV",
  "LMG RP",
  "LWO SH",
  "JAktAG",
  "KiGAbV",
  "KWO MV",
  "FKSDVO",
  "FhG SL",
  "RHG BW",
  "MFG SH",
  "UBRegG",
  "GebrMV",
  "FPackV",
  "GasGVV",
  "KWO SL",
  "GkZ SH",
  "LDG BB",
  "FlErwV",
  "BG LSA",
  "FTG BB",
  "JAktAV",
  "AMRadV",
  "GSG BY",
  "NEhelG",
  "LVO BB",
  "LJG SH",
  "WBG HB",
  "LMvitV",
  "MauerG",
  "KonvBG",
  "EBV BY",
  "TrEinV",
  "StBerG",
  "LHO HH",
  "FTG BW",
  "LuftVG",
  "KugZuV",
  "LogopG",
  "EGLizV",
  "GGO NI",
  "BArchG",
  "WStatG",
  "KVBEVO",
  "JuSchG",
  "AufhFG",
  "KOVVwG",
  "AbrStV",
  "ZTPrSG",
  "BBahnG",
  "KWG RP",
  "EJTAnV",
  "UAG MV",
  "LWO BY",
  "KAG RP",
  "LBG MV",
  "BJagdG",
  "BPolBG",
  "EuGVVO",
  "SOG HH",
  "BauSVO",
  "HLV HE",
  "LWG BW",
  "EUZBBG",
  "BFG RP",
  "WaStrG",
  "EGStPO",
  "FinRVV",
  "RHG SL",
  "HZV BY",
  "KastrG",
  "GGVSEB",
  "PolioV",
  "LHO SH",
  "BVO RP",
  "WahrnV",
  "SGleiG",
  "BtRegV",
  "EinSiG",
  "SOG MV",
  "MWDVDV",
  "AGO BY",
  "PNUPZV",
  "KGG SL",
  "LwAnpG",
  "GbAusV",
  "LBG RP",
  "UAG RP",
  "PAuswG",
  "LWG HE",
  "EUZBLG",
  "LHO HB",
  "WiStrG",
  "EuVTVO",
  "FlurbG",
  "PAG BY",
  "EWIVAG",
  "StaRUG",
  "MessEV",
  "EnWPrV",
  "StrbEG",
  "NotVPV",
  "OBG TH",
  "GOL HE",
  "PKBaSV",
  "HWG HH",
  "FTG MV",
  "HzG BB",
  "GlG MV",
  "BetrKV",
  "BDBOSG",
  "NGG NI",
  "MaStRV",
  "AWZROV",
  "LHO SL",
  "FSAAKV",
  "ParlBG",
  "DBeglG",
  "JAG HE",
  "KAG SL",
  "VerklV",
  "FwG BW",
  "MuSchG",
  "FinDAG",
  "MPAMIV",
  "KWG HE",
  "EntgFG",
  "ArbZRG",
  "LAG SL",
  "OrdenG",
  "LHO BW",
  "PostLV",
  "LOG SL",
  "FVerlV",
  "KPG MV",
  "BeurkG",
  "AusglV",
  "GKV BW",
  "UAG SH",
  "LWO HE",
  "KAG HE",
  "LDG BW",
  "MFG RP",
  "MighEV",
  "BSchAV",
  "TabStV",
  "RHG HH",
  "FoVHgV",
  "RDG MV",
  "SeeGVG",
  "HBO HE",
  "RiG SL",
  "ERechV",
  "SKBPRV",
  "RHG RP",
  "TSEAMV",
  "LWG BY",
  "LDO BW",
  "FamGKG",
  "PreisG",
  "UmwStG",
  "ArchLG",
  "VaG MV",
  "SpTrUG",
  "DMBilG",
  "BAVBVO",
  "LuftVO",
  "LWO RP",
  "AufbhG",
  "APflQG",
  "LWG RP",
  "JAG SL",
  "MeAnlG",
  "NWG NI",
  "MFG BW",
  "NRG BW",
  "AltTZG",
  "PBZugV",
  "FAG BW",
  "ErbStG",
  "MuMBek",
  "AuswSG",
  "NutzEV",
  "JAO HE",
  "ESanMV",
  "KWO HE",
  "WasSiG",
  "FuttMV",
  "DRG BW",
  "GOBRat",
  "KapMuG",
  "AbfAEV",
  "SeefiV",
  "StBAPO",
  "BWaldG",
  "DO LSA",
  "POG BY",
  "NetzDG",
  "BStatG",
  "BetrVG",
  "TabStG",
  "GO NRW",
  "BEZNG",
  "EuGHG",
  "LFBAG",
  "WeinG",
  "EVPGV",
  "WiStG",
  "HIVHG",
  "LEntG",
  "PflZV",
  "SchSG",
  "EnSiG",
  "PBefG",
  "AAppO",
  "UG SL",
  "BKnEG",
  "PassG",
  "BAFAG",
  "WG BW",
  "DGIAG",
  "WiSiV",
  "StVZO",
  "TamPV",
  "BwHFV",
  "BtMVV",
  "ZPOEG",
  "WoZSV",
  "OpfBG",
  "BPflV",
  "PKHFV",
  "FinSV",
  "SolvV",
  "HG BY",
  "EGZVG",
  "IRegG",
  "ZVALG",
  "DVStB",
  "MfnvV",
  "SchSV",
  "AnlBV",
  "RPflG",
  "KonfV",
  "PassV",
  "StBVV",
  "MgFSG",
  "LMZDV",
  "PublG",
  "ZISAG",
  "WeinV",
  "BSWAG",
  "HopfG",
  "StIdV",
  "BfAAG",
  "AMRAV",
  "AsylG",
  "REITG",
  "WiSiG",
  "QVWSG",
  "BsGaV",
  "OrthV",
  "EAMIV",
  "KonsG",
  "KfzHV",
  "GO SN",
  "VIFGG",
  "LastG",
  "BRPHV",
  "BEVVG",
  "ESchG",
  "TFGMV",
  "UKlaG",
  "StipV",
  "TrDGV",
  "GenDG",
  "BerHG",
  "TAppV",
  "EnVKG",
  "BImAG",
  "KARBV",
  "EUrlV",
  "PpUGV",
  "KHSFV",
  "BBesG",
  "OStrV",
  "PostG",
  "BattG",
  "WaffG",
  "VISZG",
  "AGebV",
  "DJubV",
  "LVwZG",
  "HKStG",
  "MTSKV",
  "UmwRG",
  "EGBGB",
  "ChemG",
  "FStrG",
  "SGFFG",
  "KostO",
  "AGVIG",
  "TDDDG",
  "GmbHG",
  "MeMBV",
  "RAVPV",
  "KErzG",
  "EG HH",
  "AEntG",
  "TBelV",
  "LV BW",
  "BUZAV",
  "ArbGG",
  "DiPAV",
  "KV MV",
  "BRiNV",
  "BNotO",
  "PflAV",
  "GesLV",
  "BKatV",
  "DSLBS",
  "VersG",
  "LWoFG",
  "EPPSG",
  "EJKoV",
  "KtEfV",
  "FreqV",
  "UAGBV",
  "BzBlG",
  "EStDV",
  "EGHGB",
  "LwVfG",
  "ZwVwV",
  "BoSoG",
  "AtVfV",
  "WAStG",
  "InvKG",
  "EWPBG",
  "EnVKV",
  "DSGVO",
  "eIDKG",
  "AbLaV",
  "ERegG",
  "BEMFV",
  "UmstG",
  "PlfZV",
  "UnifV",
  "NELEV",
  "HRFEG",
  "AMWHV",
  "HPflG",
  "AtSMV",
  "DKfAG",
  "BMinG",
  "DiGAV",
  "PKGrG",
  "PUDLV",
  "AbgrV",
  "IntVG",
  "BauPG",
  "BUrlG",
  "UrhWG",
  "BASIG",
  "OGewV",
  "VStGB",
  "AbwAG",
  "KStDV",
  "AGGVG",
  "FoVDV",
  "MBPlG",
  "EBKrG",
  "EAKAV",
  "BLESV",
  "RSFAV",
  "StipG",
  "AFGBV",
  "SBGWV",
  "MRegV",
  "PAngV",
  "SortG",
  "KAusG",
  "SCEAG",
  "HintO",
  "BBVLG",
  "BKADV",
  "BfkEG",
  "LAbfG",
  "BwBBG",
  "KCanG",
  "BeglV",
  "SubvG",
  "FFVAV",
  "HintG",
  "SchKG",
  "StabG",
  "EPSPV",
  "FamFG",
  "DVSUG",
  "BierV",
  "SodEG",
  "LKJHG",
  "ArbZG",
  "ZollV",
  "AGOZV",
  "TVGDV",
  "WGSVG",
  "VermG",
  "AWPrV",
  "GrStG",
  "GastG",
  "SeeLG",
  "StDAV",
  "AuRAG",
  "CanBV",
  "LOWiG",
  "PPDAV",
  "KG BY",
  "BBPlG",
  "FPfZG",
  "GesRV",
  "SEFFV",
  "DBGrG",
  "VwDVG",
  "FlUUG",
  "UKlaV",
  "EltSV",
  "ReblV",
  "EBSiV",
  "VRegV",
  "LAnzV",
  "IDNrG",
  "VwVfG",
  "WRegV",
  "EZulV",
  "LMIDV",
  "DIMRG",
  "EuPAG",
  "GenTG",
  "FZulG",
  "SaatG",
  "DBAnO",
  "EGGVG",
  "PartG",
  "AgNwV",
  "SUrlV",
  "PBAZV",
  "InsVV",
  "TestV",
  "BGebG",
  "EnEfG",
  "SolZG",
  "WPflG",
  "BHV1V",
  "ARegV",
  "BauGB",
  "PflVG",
  "EGovG",
  "LGebG",
  "HZvNG",
  "TKMoG",
  "WStBG",
  "SchlG",
  "EGVVG",
  "MiLoG",
  "ZerlG",
  "EGZPO",
  "FELEG",
  "eWpRV",
  "AFWoG",
  "StrEG",
  "VorgV",
  "FAnpG",
  "EthRG",
  "VSVgV",
  "APMAG",
  "WoFlV",
  "GO SH",
  "StaaV",
  "UStDV",
  "HkNRG",
  "RDGEG",
  "HeimG",
  "ArbSV",
  "WFStG",
  "AnFrV",
  "SCEBG",
  "VerlG",
  "HygPV",
  "KiTaG",
  "GasSV",
  "PStTG",
  "TTDSG",
  "WRegG",
  "KSchG",
  "GO BY",
  "BPolG",
  "AGBGB",
  "DPMAV",
  "EnLAG",
  "BVwAG",
  "LVwVG",
  "SchuV",
  "ZKBSV",
  "WpDPV",
  "AltGG",
  "NABEG",
  "PflBG",
  "GeoZG",
  "EGRDG",
  "SchVG",
  "TzBfG",
  "FrizV",
  "EUTBV",
  "PAngG",
  "HUrlV",
  "BATZV",
  "EuRAG",
  "AO SH",
  "BFSGV",
  "GKVFG",
  "EinhV",
  "LKonV",
  "FoVZV",
  "NotFV",
  "SchRG",
  "VStRG",
  "ZKDSG",
  "StBAG",
  "BVDVV",
  "BZEV",
  "NiSV",
  "EAZV",
  "KfbG",
  "RSAV",
  "VKVV",
  "AMHV",
  "ZSHG",
  "MADG",
  "PatV",
  "BtMG",
  "ZDVG",
  "PatG",
  "BECV",
  "AMbG",
  "PTAG",
  "BORA",
  "SVRV",
  "BTHG",
  "MPAV",
  "FANG",
  "DHMG",
  "AtEV",
  "ZIEV",
  "GIGV",
  "DNBG",
  "DRKG",
  "FSBV",
  "UmwG",
  "FKAG",
  "DEFG",
  "ApoG",
  "UVAV",
  "EBIG",
  "KfWG",
  "AbwV",
  "FAVO",
  "JFDG",
  "IFGO",
  "UBAG",
  "TfPV",
  "KStG",
  "EnWG",
  "NemV",
  "StZG",
  "FFGV",
  "VKFV",
  "PKEV",
  "ZESV",
  "GewO",
  "WRMG",
  "AFIV",
  "UStG",
  "UrhG",
  "ABBV",
  "SpFV",
  "BLBV",
  "BBhV",
  "EFPV",
  "TKMV",
  "BewG",
  "FSAV",
  "UVSV",
  "TAMG",
  "KJHG",
  "PKHG",
  "ELFG",
  "BRRG",
  "WpPG",
  "KHKG",
  "WBVG",
  "StrG",
  "SoZV",
  "KBFG",
  "WpIG",
  "HZvG",
  "DepV",
  "EVPG",
  "ZVFV",
  "BKGG",
  "KDAV",
  "AFuV",
  "ALFV",
  "ResG",
  "NiSG",
  "KHNG",
  "UERV",
  "KBAG",
  "CsgG",
  "EBRG",
  "BfJG",
  "BQFG",
  "Verf",
  "SVWO",
  "RiWG",
  "IVSG",
  "RegG",
  "BGSG",
  "BRKG",
  "PolG",
  "BLEG",
  "HebG",
  "FGlG",
  "HSEG",
  "SZVV",
  "EMFV",
  "LFGB",
  "GPSG",
  "GVFV",
  "ESiV",
  "SEAG",
  "GRWG",
  "DbAG",
  "KWMV",
  "ZVsG",
  "EuWO",
  "TLMV",
  "GaVO",
  "PodG",
  "EmoG",
  "PDLV",
  "EEAV",
  "LSpV",
  "BfAG",
  "AnlV",
  "VSBG",
  "RSFV",
  "GVFG",
  "IfSG",
  "EBPV",
  "EuWG",
  "MMVO",
  "GenG",
  "SanG",
  "NDWV",
  "EgVV",
  "LkSG",
  "WKBG",
  "StGB",
  "BABG",
  "LDSG",
  "MTBG",
  "AtAV",
  "FGNV",
  "BRHG",
  "PFAV",
  "AGeV",
  "OWiG",
  "VBVG",
  "BVFG",
  "UVPG",
  "KWKG",
  "ThUG",
  "EWSG",
  "BEHV",
  "GGBV",
  "ASiG",
  "AMVV",
  "AZAV",
  "IntV",
  "KDVG",
  "PStG",
  "ZSKG",
  "EnFG",
  "AEUV",
  "ATZV",
  "UZwG",
  "SEBG",
  "EfbV",
  "KGSG",
  "OGAV",
  "RBEG",
  "KSpG",
  "SAZV",
  "BtBG",
  "PIDV",
  "GAKG",
  "GemO",
  "VFZV",
  "eKFV",
  "CSCG",
  "AFBG",
  "StVO",
  "MKSV",
  "BLES",
  "PStV",
  "StFG",
  "ABAG",
  "NTSG",
  "KHBV",
  "BUKG",
  "BVAG",
  "DRiG",
  "PrKG",
  "InsO",
  "VDuG",
  "QEWV",
  "BFDG",
  "HOAI",
  "MPDG",
  "AABG",
  "ZKAV",
  "AnfG",
  "GKAR",
  "AKNV",
  "EhfG",
  "AdKG",
  "ZTRV",
  "VwVG",
  "DmMV",
  "BDWV",
  "FuAG",
  "BfRG",
  "EGAO",
  "SvEV",
  "MPhG",
  "GaFG",
  "GPEV",
  "GASV",
  "AStG",
  "AFIG",
  "MsbG",
  "WoFG",
  "UBGG",
  "AMPV",
  "BtOG",
  "ESGV",
  "AktG",
  "LUIG",
  "StAG",
  "NKRG",
  "ATDG",
  "ElmV",
  "GRCh",
  "FoVG",
  "LSpG",
  "NpSG",
  "BSIG",
  "LMEV",
  "LiqV",
  "WoGG",
  "ITFG",
  "GOBT",
  "KrWG",
  "AHGV",
  "LBGS",
  "GEIG",
  "ESVG",
  "BTHO",
  "ZFdG",
  "MTAG",
  "LFGG",
  "ESBO",
  "KAGB",
  "MaBV",
  "AGBG",
  "GrwV",
  "LNGV",
  "EStG",
  "OnWV",
  "BNDG",
  "WpAV",
  "AwSV",
  "AZRG",
  "ATGV",
  "KGUG",
  "StVG",
  "NDAV",
  "EIGV",
  "VwGO",
  "THWG",
  "AFSG",
  "ZVEG",
  "STzV",
  "RhmV",
  "BRBG",
  "BZRG",
  "VkVO",
  "MgvG",
  "KSVG",
  "DSPV",
  "VZVV",
  "BEHG",
  "FHKV",
  "VWDG",
  "BFSG",
  "DWDG",
  "DHRV",
  "JVEG",
  "EMVG",
  "HofV",
  "BRAO",
  "StPO",
  "AVAG",
  "KVAV",
  "WMVO",
  "HWiG",
  "WUFG",
  "BBiG",
  "EPSV",
  "WoGV",
  "EgVG",
  "FlRG",
  "VStG",
  "eWpG",
  "AFRG",
  "OASG",
  "BADV",
  "BKRG",
  "MAKV",
  "BKAG",
  "AbgG",
  "DIFG",
  "VZOG",
  "BBKG",
  "BDSG",
  "KfWV",
  "HGrG",
  "LMHV",
  "MbBO",
  "HNSG",
  "LNGG",
  "KTFG",
  "KVMG",
  "KVKG",
  "FlRV",
  "FzTV",
  "VwZG",
  "AnzV",
  "SVHV",
  "KPBV",
  "BVLG",
  "WStG",
  "DOHG",
  "KVBG",
  "WpHG",
  "GBMG",
  "SekG",
  "SigG",
  "UPAG",
  "SZAG",
  "ERVV",
  "TEHG",
  "GEEV",
  "BApO",
  "EALG",
  "AMVO",
  "PUAG",
  "BAFG",
  "BStV",
  "BEEG",
  "LBAV",
  "RfBV",
  "StUG",
  "IHKG",
  "MFG",
  "ARG",
  "BGB",
  "KBV",
  "WVO",
  "ALV",
  "SGG",
  "IFG",
  "LTV",
  "SiV",
  "USG",
  "KVR",
  "GEG",
  "LBO",
  "EUV",
  "VVG",
  "SpG",
  "HAV",
  "AUV",
  "ALG",
  "KAV",
  "UIG",
  "KHG",
  "FGG",
  "AUG",
  "PAO",
  "UBG",
  "FAG",
  "WGV",
  "ZVG",
  "GKG",
  "WVG",
  "KIV",
  "RSG",
  "KAE",
  "WTV",
  "AtG",
  "HwO",
  "WSG",
  "KOV",
  "GVG",
  "BKV",
  "SUV",
  "GbV",
  "SUG",
  "KAG",
  "ASG",
  "MHG",
  "WPO",
  "KHV",
  "JGG",
  "KSG",
  "VDV",
  "ARV",
  "TPG",
  "ZVO",
  "EVO",
  "SVG",
  "BDG",
  "ZIV",
  "TMG",
  "AWG",
  "TVG",
  "GOT",
  "GSG",
  "MZG",
  "ROG",
  "GBV",
  "HRG",
  "VbF",
  "FSV",
  "WRV",
  "UVG",
  "LKV",
  "BEG",
  "VRV",
  "WDO",
  "BtG",
  "SBG",
  "EEG",
  "SHV",
  "VGG",
  "RDV",
  "TSG",
  "LVG",
  "TAV",
  "OEG",
  "TfV",
  "EJG",
  "RVO",
  "TDG",
  "BBG",
  "FVG",
  "WHG",
  "PSG",
  "HRV",
  "GGV",
  "ZPO",
  "FTG",
  "GWB",
  "GBO",
  "LwG",
  "BMG",
  "BLG",
  "AAG",
  "HGB",
  "GOP",
  "RZV",
  "ZDG",
  "MDV",
  "VBD",
  "SPV",
  "LBG",
  "TGV",
  "PRV",
  "BWO",
  "MOG",
  "AMG",
  "URV",
  "DDG",
  "SLV",
  "SEG",
  "AZG",
  "GwG",
  "VIG",
  "NRG",
  "ZHG",
  "VRG",
  "AVV",
  "IRG",
  "ZAG",
  "NAV",
  "VgV",
  "AMV",
  "EBV",
  "FFG",
  "BHO",
  "ELV",
  "ODV",
  "HHG",
  "BVG",
  "FGO",
  "OZG",
  "BLV",
  "TFG",
  "UAG",
  "NLV",
  "WEG",
  "EBO",
  "MsV",
  "GOZ",
  "FlG",
  "ZKG",
  "WOS",
  "FZV",
  "DWG",
  "RoV",
  "BNV",
  "WBO",
  "EEV",
  "GIV",
  "DNG",
  "ABV",
  "VWG",
  "AdG",
  "ZMV",
  "AGG",
  "FRG",
  "MUV",
  "UkV",
  "PBV",
  "GVO",
  "GVV",
  "TNV",
  "LAG",
  "AWV",
  "HWG",
  "RDG",
  "FeV",
  "MRK",
  "AHG",
  "GAD",
  "WPG",
  "MWV",
  "MPG",
  "SRV",
  "RVG",
  "AKG",
  "LSV",
  "KKG",
  "GPV",
  "AFG",
  "GRG",
  "SAG",
  "HAG",
  "BVV",
  "AZV",
  "AEG",
  "BGG",
  "VDG",
  "KmV",
  "TKG",
  "KWG",
  "VAG",
  "UWG",
  "WO",
  "EV",
  "EG",
  "GG",
  "AO",
  "MV",
  "EU",
  "SG"
];